# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v1
kind: Pod
metadata:
  name: example-nodejs
spec:
  containers:
    - name: example-nodejs
      image: example-nodejs:1
      imagePullPolicy: Never
