# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra"

gem "puma"

gem "pg"
