#!/usr/bin/env bash
# ouputs a new list of aws regions to a JS util file
# requires the aws cli to be installed and authenticated

declare -r UTIL_DIR="$(dirname $0)/../addon/utils"
declare -r REGION_LIST_NAME="aws-region-list.js"

function create_region_list {
  (
    cd "$UTIL_DIR"
    {
      printf '//DO NOT EDIT
//THIS FILE IS AUTOGENERATED BY scripts/generate-aws-region-list.sh

export default '
      aws ec2 describe-regions --all-regions --query "Regions[].RegionName" | \
      sed -e '$s/$/;/' # insert `;` before final `\n`
    } > "$REGION_LIST_NAME"
  )
}

create_region_list
