# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

language: go
go:
  - 1.13
  - 1.14.1
env:
  - GOARCH: amd64
  - GOARCH: 386
script:
  - go test -v
notifications:
  email:
    recipients:
      - brian.downs@gmail.com
    on_success: change
    on_failure: always
