name: notify_main_failure
runs:
  using: composite
  steps:
  - name: Notify failures on main branch
    run: |-
      if [ "${{ github.ref }}" == "main" ]; then
        curl -X POST -H 'Content-type: application/json' \
        --data \
        "{ \
          \"text\": \":warning: Failed job on branch _${{ github.ref }}_\", \
          \"attachments\": [ \
            { \
              \"fallback\": \":warning: Failed job on branch _${{ github.ref }}_\", \
              \"fields\": [ \
                  { \
                      \"title\": \"User\", \
                      \"value\": \"${{ github.actor }}\", \
                      \"short\": \"true\" \
                  }, \
                  { \
                      \"title\": \"Merge commit\", \
                      \"value\": \"<https://github.com/${CIRCLE_PROJECT_USERNAME}/${{ github.repository }}/commit/${{ github.sha }}|$(echo ${{ github.sha }} | cut -c1-10)>\", \
                      \"short\": \"true\" \
                  }, \
                  { \
                      \"title\": \"Failed job\", \
                      \"value\": \"<${CIRCLE_BUILD_URL}|${{ github.job }}>\", \
                      \"short\": \"true\" \
                  }, \
                  { \
                      \"title\": \"Full Workflow\", \
                      \"value\": \"<https://circleci.com/workflow-run/${{ github.run_number }}|${CIRCLE_PROJECT_USERNAME}/${{ github.repository }}>\", \
                      \"short\": \"true\" \
                  } \
              ], \
              \"ts\": \"$(date +%s)\", \
              \"color\": \"danger\" \
            } \
          ] \
        }" ${SLACK_WEBHOOK}
      fi
    if: failure()
    shell: bash