// Code generated by protoc-gen-go. DO NOT EDIT.
// source: builder.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Args are the common argument types that are available to many of the
// dynamic functions. The exact list of available argument types is available
// on the Go interface docs.
type Args struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args) Reset()         { *m = Args{} }
func (m *Args) String() string { return proto.CompactTextString(m) }
func (*Args) ProtoMessage()    {}
func (*Args) Descriptor() ([]byte, []int) {
	return fileDescriptor_builder_48e7186ce11bf882, []int{0}
}
func (m *Args) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args.Unmarshal(m, b)
}
func (m *Args) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args.Marshal(b, m, deterministic)
}
func (dst *Args) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args.Merge(dst, src)
}
func (m *Args) XXX_Size() int {
	return xxx_messageInfo_Args.Size(m)
}
func (m *Args) XXX_DiscardUnknown() {
	xxx_messageInfo_Args.DiscardUnknown(m)
}

var xxx_messageInfo_Args proto.InternalMessageInfo

// See component.Source
type Args_Source struct {
	App                  string   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_Source) Reset()         { *m = Args_Source{} }
func (m *Args_Source) String() string { return proto.CompactTextString(m) }
func (*Args_Source) ProtoMessage()    {}
func (*Args_Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_builder_48e7186ce11bf882, []int{0, 0}
}
func (m *Args_Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_Source.Unmarshal(m, b)
}
func (m *Args_Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_Source.Marshal(b, m, deterministic)
}
func (dst *Args_Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_Source.Merge(dst, src)
}
func (m *Args_Source) XXX_Size() int {
	return xxx_messageInfo_Args_Source.Size(m)
}
func (m *Args_Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Args_Source proto.InternalMessageInfo

func (m *Args_Source) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Args_Source) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Build struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_builder_48e7186ce11bf882, []int{1}
}
func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (dst *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(dst, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

type Build_Args struct {
	// args is the list of argument types. This will include some of the
	// standard types in this file as well as custom types declared by
	// the func spec.
	Args                 []*any.Any `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Build_Args) Reset()         { *m = Build_Args{} }
func (m *Build_Args) String() string { return proto.CompactTextString(m) }
func (*Build_Args) ProtoMessage()    {}
func (*Build_Args) Descriptor() ([]byte, []int) {
	return fileDescriptor_builder_48e7186ce11bf882, []int{1, 0}
}
func (m *Build_Args) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build_Args.Unmarshal(m, b)
}
func (m *Build_Args) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build_Args.Marshal(b, m, deterministic)
}
func (dst *Build_Args) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build_Args.Merge(dst, src)
}
func (m *Build_Args) XXX_Size() int {
	return xxx_messageInfo_Build_Args.Size(m)
}
func (m *Build_Args) XXX_DiscardUnknown() {
	xxx_messageInfo_Build_Args.DiscardUnknown(m)
}

var xxx_messageInfo_Build_Args proto.InternalMessageInfo

func (m *Build_Args) GetArgs() []*any.Any {
	if m != nil {
		return m.Args
	}
	return nil
}

type Build_Resp struct {
	Result               *any.Any `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build_Resp) Reset()         { *m = Build_Resp{} }
func (m *Build_Resp) String() string { return proto.CompactTextString(m) }
func (*Build_Resp) ProtoMessage()    {}
func (*Build_Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_builder_48e7186ce11bf882, []int{1, 1}
}
func (m *Build_Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build_Resp.Unmarshal(m, b)
}
func (m *Build_Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build_Resp.Marshal(b, m, deterministic)
}
func (dst *Build_Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build_Resp.Merge(dst, src)
}
func (m *Build_Resp) XXX_Size() int {
	return xxx_messageInfo_Build_Resp.Size(m)
}
func (m *Build_Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Build_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Build_Resp proto.InternalMessageInfo

func (m *Build_Resp) GetResult() *any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

// Empty is just an empty message useful with some RPC endpoints.
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_builder_48e7186ce11bf882, []int{2}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// FuncSpec describes a function and is used by the dependency-injection
// framework to provide the function with the proper values.
//
// Value types are specified using strings. Built-in framework types
// are defined via constants in the `sdk` package. For custom types, you
// can use whatever string as long as it is unique. We recommend using a
// unique prefix plus the Go type name.
type FuncSpec struct {
	Args                 []string `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuncSpec) Reset()         { *m = FuncSpec{} }
func (m *FuncSpec) String() string { return proto.CompactTextString(m) }
func (*FuncSpec) ProtoMessage()    {}
func (*FuncSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_builder_48e7186ce11bf882, []int{3}
}
func (m *FuncSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncSpec.Unmarshal(m, b)
}
func (m *FuncSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncSpec.Marshal(b, m, deterministic)
}
func (dst *FuncSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncSpec.Merge(dst, src)
}
func (m *FuncSpec) XXX_Size() int {
	return xxx_messageInfo_FuncSpec.Size(m)
}
func (m *FuncSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncSpec.DiscardUnknown(m)
}

var xxx_messageInfo_FuncSpec proto.InternalMessageInfo

func (m *FuncSpec) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *FuncSpec) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Args)(nil), "proto.Args")
	proto.RegisterType((*Args_Source)(nil), "proto.Args.Source")
	proto.RegisterType((*Build)(nil), "proto.Build")
	proto.RegisterType((*Build_Args)(nil), "proto.Build.Args")
	proto.RegisterType((*Build_Resp)(nil), "proto.Build.Resp")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*FuncSpec)(nil), "proto.FuncSpec")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuilderClient is the client API for Builder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuilderClient interface {
	BuildSpec(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FuncSpec, error)
	Build(ctx context.Context, in *Build_Args, opts ...grpc.CallOption) (*Build_Resp, error)
}

type builderClient struct {
	cc *grpc.ClientConn
}

func NewBuilderClient(cc *grpc.ClientConn) BuilderClient {
	return &builderClient{cc}
}

func (c *builderClient) BuildSpec(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FuncSpec, error) {
	out := new(FuncSpec)
	err := c.cc.Invoke(ctx, "/proto.Builder/BuildSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderClient) Build(ctx context.Context, in *Build_Args, opts ...grpc.CallOption) (*Build_Resp, error) {
	out := new(Build_Resp)
	err := c.cc.Invoke(ctx, "/proto.Builder/Build", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuilderServer is the server API for Builder service.
type BuilderServer interface {
	BuildSpec(context.Context, *Empty) (*FuncSpec, error)
	Build(context.Context, *Build_Args) (*Build_Resp, error)
}

func RegisterBuilderServer(s *grpc.Server, srv BuilderServer) {
	s.RegisterService(&_Builder_serviceDesc, srv)
}

func _Builder_BuildSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServer).BuildSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Builder/BuildSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServer).BuildSpec(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Builder_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Build_Args)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Builder/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServer).Build(ctx, req.(*Build_Args))
	}
	return interceptor(ctx, in, info, handler)
}

var _Builder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Builder",
	HandlerType: (*BuilderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildSpec",
			Handler:    _Builder_BuildSpec_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _Builder_Build_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "builder.proto",
}

func init() { proto.RegisterFile("builder.proto", fileDescriptor_builder_48e7186ce11bf882) }

var fileDescriptor_builder_48e7186ce11bf882 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4e, 0x84, 0x30,
	0x10, 0x86, 0x83, 0x0b, 0xac, 0x8c, 0x1a, 0x75, 0x62, 0x0c, 0xf6, 0xb4, 0xe1, 0x44, 0x8c, 0x76,
	0xcd, 0x6a, 0xf6, 0xbe, 0x9b, 0xe8, 0x03, 0xb0, 0x4f, 0x00, 0x6c, 0x45, 0x13, 0xa4, 0x4d, 0x69,
	0x0f, 0xbc, 0xbd, 0xe9, 0xb4, 0x92, 0x78, 0xd8, 0x13, 0xf3, 0x0f, 0x7f, 0xff, 0x6f, 0x66, 0xe0,
	0xaa, 0xb1, 0xdf, 0xfd, 0x51, 0x68, 0xae, 0xb4, 0x34, 0x12, 0x13, 0xfa, 0xb0, 0x87, 0x4e, 0xca,
	0xae, 0x17, 0x6b, 0x52, 0x8d, 0xfd, 0x5c, 0xd7, 0xc3, 0xe4, 0x1d, 0xc5, 0x16, 0xe2, 0x9d, 0xee,
	0x46, 0xc6, 0x21, 0x3d, 0x48, 0xab, 0x5b, 0x81, 0x37, 0xb0, 0xa8, 0x95, 0xca, 0xa3, 0x55, 0x54,
	0x66, 0x95, 0x2b, 0x11, 0x21, 0x56, 0xb5, 0xf9, 0xca, 0xcf, 0xa8, 0x45, 0x75, 0x21, 0x21, 0xd9,
	0x3b, 0x14, 0x7b, 0xf1, 0x01, 0x58, 0x42, 0x5c, 0xeb, 0x6e, 0xcc, 0xa3, 0xd5, 0xa2, 0xbc, 0xd8,
	0xdc, 0x71, 0x8f, 0xe4, 0x7f, 0x48, 0xbe, 0x1b, 0xa6, 0x8a, 0x1c, 0xec, 0x0d, 0xe2, 0x4a, 0x8c,
	0x0a, 0x9f, 0x20, 0xd5, 0x62, 0xb4, 0xbd, 0x21, 0xd6, 0xa9, 0x37, 0xc1, 0x53, 0x2c, 0x21, 0x79,
	0xff, 0x51, 0x66, 0x2a, 0xb6, 0x70, 0xfe, 0x61, 0x87, 0xf6, 0xa0, 0x44, 0xeb, 0x26, 0x9b, 0xa1,
	0x99, 0x8f, 0xc7, 0xfb, 0x39, 0xd6, 0xcf, 0x1b, 0xd4, 0xe6, 0x08, 0xcb, 0xbd, 0x3f, 0x0e, 0x3e,
	0x42, 0x46, 0x25, 0x65, 0x5c, 0x7a, 0x1e, 0xa7, 0x74, 0x76, 0x1d, 0xd4, 0x8c, 0x78, 0x0e, 0x8b,
	0xe2, 0x6d, 0xf8, 0x43, 0x8a, 0xd3, 0xd1, 0xfe, 0xb7, 0xdc, 0x52, 0x4d, 0x4a, 0x9d, 0xd7, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0xfc, 0xbf, 0x45, 0x89, 0x01, 0x00, 0x00,
}
