// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mapper.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Map struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Map) Reset()         { *m = Map{} }
func (m *Map) String() string { return proto.CompactTextString(m) }
func (*Map) ProtoMessage()    {}
func (*Map) Descriptor() ([]byte, []int) {
	return fileDescriptor_83403f8bbb3888d4, []int{0}
}

func (m *Map) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Map.Unmarshal(m, b)
}
func (m *Map) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Map.Marshal(b, m, deterministic)
}
func (m *Map) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Map.Merge(m, src)
}
func (m *Map) XXX_Size() int {
	return xxx_messageInfo_Map.Size(m)
}
func (m *Map) XXX_DiscardUnknown() {
	xxx_messageInfo_Map.DiscardUnknown(m)
}

var xxx_messageInfo_Map proto.InternalMessageInfo

type Map_Request struct {
	// args is the list of argument types.
	Args *FuncSpec_Args `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	// result is the desired result type.
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Map_Request) Reset()         { *m = Map_Request{} }
func (m *Map_Request) String() string { return proto.CompactTextString(m) }
func (*Map_Request) ProtoMessage()    {}
func (*Map_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_83403f8bbb3888d4, []int{0, 0}
}

func (m *Map_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Map_Request.Unmarshal(m, b)
}
func (m *Map_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Map_Request.Marshal(b, m, deterministic)
}
func (m *Map_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Map_Request.Merge(m, src)
}
func (m *Map_Request) XXX_Size() int {
	return xxx_messageInfo_Map_Request.Size(m)
}
func (m *Map_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Map_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Map_Request proto.InternalMessageInfo

func (m *Map_Request) GetArgs() *FuncSpec_Args {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Map_Request) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type Map_Response struct {
	// result is the mapped data type that matches the type expected
	// by the MapRequest.result field.
	Result               *any.Any `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Map_Response) Reset()         { *m = Map_Response{} }
func (m *Map_Response) String() string { return proto.CompactTextString(m) }
func (*Map_Response) ProtoMessage()    {}
func (*Map_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_83403f8bbb3888d4, []int{0, 1}
}

func (m *Map_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Map_Response.Unmarshal(m, b)
}
func (m *Map_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Map_Response.Marshal(b, m, deterministic)
}
func (m *Map_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Map_Response.Merge(m, src)
}
func (m *Map_Response) XXX_Size() int {
	return xxx_messageInfo_Map_Response.Size(m)
}
func (m *Map_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Map_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Map_Response proto.InternalMessageInfo

func (m *Map_Response) GetResult() *any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

type Map_ListResponse struct {
	// FuncSpec
	Funcs                []*FuncSpec `protobuf:"bytes,1,rep,name=funcs,proto3" json:"funcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Map_ListResponse) Reset()         { *m = Map_ListResponse{} }
func (m *Map_ListResponse) String() string { return proto.CompactTextString(m) }
func (*Map_ListResponse) ProtoMessage()    {}
func (*Map_ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83403f8bbb3888d4, []int{0, 2}
}

func (m *Map_ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Map_ListResponse.Unmarshal(m, b)
}
func (m *Map_ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Map_ListResponse.Marshal(b, m, deterministic)
}
func (m *Map_ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Map_ListResponse.Merge(m, src)
}
func (m *Map_ListResponse) XXX_Size() int {
	return xxx_messageInfo_Map_ListResponse.Size(m)
}
func (m *Map_ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Map_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Map_ListResponse proto.InternalMessageInfo

func (m *Map_ListResponse) GetFuncs() []*FuncSpec {
	if m != nil {
		return m.Funcs
	}
	return nil
}

func init() {
	proto.RegisterType((*Map)(nil), "proto.Map")
	proto.RegisterType((*Map_Request)(nil), "proto.Map.Request")
	proto.RegisterType((*Map_Response)(nil), "proto.Map.Response")
	proto.RegisterType((*Map_ListResponse)(nil), "proto.Map.ListResponse")
}

func init() {
	proto.RegisterFile("mapper.proto", fileDescriptor_83403f8bbb3888d4)
}

var fileDescriptor_83403f8bbb3888d4 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0xa5, 0xce, 0x55, 0xbd, 0x2d, 0x08, 0x51, 0xe6, 0x8c, 0x2f, 0x43, 0x10, 0xfa, 0x20, 0x19,
	0x54, 0x04, 0x9f, 0x84, 0x3d, 0xe8, 0x8b, 0xf6, 0x25, 0xfe, 0x82, 0xac, 0x64, 0x61, 0xd0, 0x25,
	0x31, 0x1f, 0xe0, 0x7e, 0x9f, 0x7f, 0x4c, 0x9a, 0xb4, 0xc5, 0x75, 0x4f, 0x97, 0x73, 0xcf, 0xb9,
	0xe7, 0x1e, 0x0e, 0xe4, 0x3b, 0xa6, 0x35, 0x37, 0x44, 0x1b, 0xe5, 0x14, 0x9a, 0x86, 0x81, 0x6f,
	0x85, 0x52, 0xa2, 0xe1, 0xcb, 0x80, 0xd6, 0x7e, 0xb3, 0x64, 0x72, 0x1f, 0x15, 0xf8, 0x6e, 0x4c,
	0xf1, 0x9d, 0x76, 0x3d, 0x99, 0xeb, 0xc6, 0x8b, 0xad, 0x8c, 0xe8, 0xfe, 0x37, 0x81, 0x49, 0xc5,
	0x34, 0xfe, 0x80, 0x33, 0xca, 0xbf, 0x3d, 0xb7, 0x0e, 0x15, 0x70, 0xca, 0x8c, 0xb0, 0xf3, 0x64,
	0x91, 0x14, 0x59, 0x79, 0x1d, 0x85, 0xe4, 0xdd, 0xcb, 0xfa, 0x4b, 0xf3, 0x9a, 0xac, 0x8c, 0xb0,
	0x34, 0x28, 0xd0, 0x0c, 0x52, 0xc3, 0xad, 0x6f, 0xdc, 0xfc, 0x64, 0x91, 0x14, 0x17, 0xb4, 0x43,
	0xf8, 0x05, 0xce, 0x29, 0xb7, 0x5a, 0x49, 0xcb, 0xd1, 0xe3, 0xa0, 0xe9, 0xfd, 0x62, 0x38, 0xd2,
	0x87, 0x23, 0x2b, 0xb9, 0x1f, 0x2e, 0x9f, 0x21, 0xff, 0xdc, 0x5a, 0x37, 0x5c, 0x3f, 0xc0, 0x74,
	0xe3, 0x65, 0xdd, 0x86, 0x99, 0x14, 0x59, 0x79, 0x39, 0x0a, 0x43, 0x23, 0x5b, 0xfe, 0x40, 0x5a,
	0x85, 0x8a, 0xd0, 0x2b, 0x64, 0xad, 0x41, 0x44, 0x16, 0xcd, 0x8e, 0xbe, 0xbd, 0xb5, 0x55, 0xe0,
	0x9b, 0xce, 0xa8, 0x62, 0x9a, 0x1c, 0x3c, 0x24, 0xa1, 0x0e, 0x84, 0xfe, 0xf1, 0x5d, 0x2f, 0xf8,
	0xea, 0x60, 0x17, 0xf5, 0xeb, 0x34, 0xec, 0x9e, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x76,
	0x51, 0x0d, 0xa3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MapperClient is the client API for Mapper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MapperClient interface {
	// ListMappers returns the list of mappers that this plugin supports.
	ListMappers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Map_ListResponse, error)
	// Map executes a mapper.
	Map(ctx context.Context, in *Map_Request, opts ...grpc.CallOption) (*Map_Response, error)
}

type mapperClient struct {
	cc grpc.ClientConnInterface
}

func NewMapperClient(cc grpc.ClientConnInterface) MapperClient {
	return &mapperClient{cc}
}

func (c *mapperClient) ListMappers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Map_ListResponse, error) {
	out := new(Map_ListResponse)
	err := c.cc.Invoke(ctx, "/proto.Mapper/ListMappers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapperClient) Map(ctx context.Context, in *Map_Request, opts ...grpc.CallOption) (*Map_Response, error) {
	out := new(Map_Response)
	err := c.cc.Invoke(ctx, "/proto.Mapper/Map", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapperServer is the server API for Mapper service.
type MapperServer interface {
	// ListMappers returns the list of mappers that this plugin supports.
	ListMappers(context.Context, *empty.Empty) (*Map_ListResponse, error)
	// Map executes a mapper.
	Map(context.Context, *Map_Request) (*Map_Response, error)
}

// UnimplementedMapperServer can be embedded to have forward compatible implementations.
type UnimplementedMapperServer struct {
}

func (*UnimplementedMapperServer) ListMappers(ctx context.Context, req *empty.Empty) (*Map_ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMappers not implemented")
}
func (*UnimplementedMapperServer) Map(ctx context.Context, req *Map_Request) (*Map_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Map not implemented")
}

func RegisterMapperServer(s *grpc.Server, srv MapperServer) {
	s.RegisterService(&_Mapper_serviceDesc, srv)
}

func _Mapper_ListMappers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapperServer).ListMappers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Mapper/ListMappers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapperServer).ListMappers(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mapper_Map_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Map_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapperServer).Map(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Mapper/Map",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapperServer).Map(ctx, req.(*Map_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mapper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Mapper",
	HandlerType: (*MapperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMappers",
			Handler:    _Mapper_ListMappers_Handler,
		},
		{
			MethodName: "Map",
			Handler:    _Mapper_Map_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mapper.proto",
}
