// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import protostructure "github.com/mitchellh/protostructure"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Args are the common argument types that are available to many of the
// dynamic functions. The exact list of available argument types is available
// on the Go interface docs.
type Args struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args) Reset()         { *m = Args{} }
func (m *Args) String() string { return proto.CompactTextString(m) }
func (*Args) ProtoMessage()    {}
func (*Args) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0}
}
func (m *Args) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args.Unmarshal(m, b)
}
func (m *Args) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args.Marshal(b, m, deterministic)
}
func (dst *Args) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args.Merge(dst, src)
}
func (m *Args) XXX_Size() int {
	return xxx_messageInfo_Args.Size(m)
}
func (m *Args) XXX_DiscardUnknown() {
	xxx_messageInfo_Args.DiscardUnknown(m)
}

var xxx_messageInfo_Args proto.InternalMessageInfo

// See component.Source
type Args_Source struct {
	// app is the name of the application being deployed.
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// path is the absolute directory path to the root directory for source files.
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_Source) Reset()         { *m = Args_Source{} }
func (m *Args_Source) String() string { return proto.CompactTextString(m) }
func (*Args_Source) ProtoMessage()    {}
func (*Args_Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0, 0}
}
func (m *Args_Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_Source.Unmarshal(m, b)
}
func (m *Args_Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_Source.Marshal(b, m, deterministic)
}
func (dst *Args_Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_Source.Merge(dst, src)
}
func (m *Args_Source) XXX_Size() int {
	return xxx_messageInfo_Args_Source.Size(m)
}
func (m *Args_Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Args_Source proto.InternalMessageInfo

func (m *Args_Source) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Args_Source) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// See component.DeploymentConfig
type Args_DeploymentConfig struct {
	ServerAddr           string   `protobuf:"bytes,1,opt,name=server_addr,json=serverAddr,proto3" json:"server_addr,omitempty"`
	ServerInsecure       bool     `protobuf:"varint,2,opt,name=server_insecure,json=serverInsecure,proto3" json:"server_insecure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_DeploymentConfig) Reset()         { *m = Args_DeploymentConfig{} }
func (m *Args_DeploymentConfig) String() string { return proto.CompactTextString(m) }
func (*Args_DeploymentConfig) ProtoMessage()    {}
func (*Args_DeploymentConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0, 1}
}
func (m *Args_DeploymentConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_DeploymentConfig.Unmarshal(m, b)
}
func (m *Args_DeploymentConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_DeploymentConfig.Marshal(b, m, deterministic)
}
func (dst *Args_DeploymentConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_DeploymentConfig.Merge(dst, src)
}
func (m *Args_DeploymentConfig) XXX_Size() int {
	return xxx_messageInfo_Args_DeploymentConfig.Size(m)
}
func (m *Args_DeploymentConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_DeploymentConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Args_DeploymentConfig proto.InternalMessageInfo

func (m *Args_DeploymentConfig) GetServerAddr() string {
	if m != nil {
		return m.ServerAddr
	}
	return ""
}

func (m *Args_DeploymentConfig) GetServerInsecure() bool {
	if m != nil {
		return m.ServerInsecure
	}
	return false
}

// DataDir represents the directory where data can be stored. This is an internal
// struct and shouldn't be used directly. Use the relevant *datadir implementation
// instead.
type Args_DataDir struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_DataDir) Reset()         { *m = Args_DataDir{} }
func (m *Args_DataDir) String() string { return proto.CompactTextString(m) }
func (*Args_DataDir) ProtoMessage()    {}
func (*Args_DataDir) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0, 2}
}
func (m *Args_DataDir) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_DataDir.Unmarshal(m, b)
}
func (m *Args_DataDir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_DataDir.Marshal(b, m, deterministic)
}
func (dst *Args_DataDir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_DataDir.Merge(dst, src)
}
func (m *Args_DataDir) XXX_Size() int {
	return xxx_messageInfo_Args_DataDir.Size(m)
}
func (m *Args_DataDir) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_DataDir.DiscardUnknown(m)
}

var xxx_messageInfo_Args_DataDir proto.InternalMessageInfo

type Args_DataDir_Project struct {
	CacheDir             string   `protobuf:"bytes,2,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	DataDir              string   `protobuf:"bytes,3,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_DataDir_Project) Reset()         { *m = Args_DataDir_Project{} }
func (m *Args_DataDir_Project) String() string { return proto.CompactTextString(m) }
func (*Args_DataDir_Project) ProtoMessage()    {}
func (*Args_DataDir_Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0, 2, 0}
}
func (m *Args_DataDir_Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_DataDir_Project.Unmarshal(m, b)
}
func (m *Args_DataDir_Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_DataDir_Project.Marshal(b, m, deterministic)
}
func (dst *Args_DataDir_Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_DataDir_Project.Merge(dst, src)
}
func (m *Args_DataDir_Project) XXX_Size() int {
	return xxx_messageInfo_Args_DataDir_Project.Size(m)
}
func (m *Args_DataDir_Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_DataDir_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Args_DataDir_Project proto.InternalMessageInfo

func (m *Args_DataDir_Project) GetCacheDir() string {
	if m != nil {
		return m.CacheDir
	}
	return ""
}

func (m *Args_DataDir_Project) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

type Args_DataDir_App struct {
	CacheDir             string   `protobuf:"bytes,2,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	DataDir              string   `protobuf:"bytes,3,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_DataDir_App) Reset()         { *m = Args_DataDir_App{} }
func (m *Args_DataDir_App) String() string { return proto.CompactTextString(m) }
func (*Args_DataDir_App) ProtoMessage()    {}
func (*Args_DataDir_App) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0, 2, 1}
}
func (m *Args_DataDir_App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_DataDir_App.Unmarshal(m, b)
}
func (m *Args_DataDir_App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_DataDir_App.Marshal(b, m, deterministic)
}
func (dst *Args_DataDir_App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_DataDir_App.Merge(dst, src)
}
func (m *Args_DataDir_App) XXX_Size() int {
	return xxx_messageInfo_Args_DataDir_App.Size(m)
}
func (m *Args_DataDir_App) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_DataDir_App.DiscardUnknown(m)
}

var xxx_messageInfo_Args_DataDir_App proto.InternalMessageInfo

func (m *Args_DataDir_App) GetCacheDir() string {
	if m != nil {
		return m.CacheDir
	}
	return ""
}

func (m *Args_DataDir_App) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

type Args_DataDir_Component struct {
	CacheDir             string   `protobuf:"bytes,2,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	DataDir              string   `protobuf:"bytes,3,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_DataDir_Component) Reset()         { *m = Args_DataDir_Component{} }
func (m *Args_DataDir_Component) String() string { return proto.CompactTextString(m) }
func (*Args_DataDir_Component) ProtoMessage()    {}
func (*Args_DataDir_Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0, 2, 2}
}
func (m *Args_DataDir_Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_DataDir_Component.Unmarshal(m, b)
}
func (m *Args_DataDir_Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_DataDir_Component.Marshal(b, m, deterministic)
}
func (dst *Args_DataDir_Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_DataDir_Component.Merge(dst, src)
}
func (m *Args_DataDir_Component) XXX_Size() int {
	return xxx_messageInfo_Args_DataDir_Component.Size(m)
}
func (m *Args_DataDir_Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_DataDir_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Args_DataDir_Component proto.InternalMessageInfo

func (m *Args_DataDir_Component) GetCacheDir() string {
	if m != nil {
		return m.CacheDir
	}
	return ""
}

func (m *Args_DataDir_Component) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

// Logger is used to construct an logger for the plugin.
type Args_Logger struct {
	// name is the name of the logger
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_Logger) Reset()         { *m = Args_Logger{} }
func (m *Args_Logger) String() string { return proto.CompactTextString(m) }
func (*Args_Logger) ProtoMessage()    {}
func (*Args_Logger) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0, 3}
}
func (m *Args_Logger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_Logger.Unmarshal(m, b)
}
func (m *Args_Logger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_Logger.Marshal(b, m, deterministic)
}
func (dst *Args_Logger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_Logger.Merge(dst, src)
}
func (m *Args_Logger) XXX_Size() int {
	return xxx_messageInfo_Args_Logger.Size(m)
}
func (m *Args_Logger) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_Logger.DiscardUnknown(m)
}

var xxx_messageInfo_Args_Logger proto.InternalMessageInfo

func (m *Args_Logger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// TerminalUI is used to construct the terminal.UI for the plugin.
type Args_TerminalUI struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_TerminalUI) Reset()         { *m = Args_TerminalUI{} }
func (m *Args_TerminalUI) String() string { return proto.CompactTextString(m) }
func (*Args_TerminalUI) ProtoMessage()    {}
func (*Args_TerminalUI) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0, 4}
}
func (m *Args_TerminalUI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_TerminalUI.Unmarshal(m, b)
}
func (m *Args_TerminalUI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_TerminalUI.Marshal(b, m, deterministic)
}
func (dst *Args_TerminalUI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_TerminalUI.Merge(dst, src)
}
func (m *Args_TerminalUI) XXX_Size() int {
	return xxx_messageInfo_Args_TerminalUI.Size(m)
}
func (m *Args_TerminalUI) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_TerminalUI.DiscardUnknown(m)
}

var xxx_messageInfo_Args_TerminalUI proto.InternalMessageInfo

// HistoryClient is used to serve the history client for the plugin.
type Args_HistoryClient struct {
	StreamId             uint32   `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_HistoryClient) Reset()         { *m = Args_HistoryClient{} }
func (m *Args_HistoryClient) String() string { return proto.CompactTextString(m) }
func (*Args_HistoryClient) ProtoMessage()    {}
func (*Args_HistoryClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0, 5}
}
func (m *Args_HistoryClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_HistoryClient.Unmarshal(m, b)
}
func (m *Args_HistoryClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_HistoryClient.Marshal(b, m, deterministic)
}
func (dst *Args_HistoryClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_HistoryClient.Merge(dst, src)
}
func (m *Args_HistoryClient) XXX_Size() int {
	return xxx_messageInfo_Args_HistoryClient.Size(m)
}
func (m *Args_HistoryClient) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_HistoryClient.DiscardUnknown(m)
}

var xxx_messageInfo_Args_HistoryClient proto.InternalMessageInfo

func (m *Args_HistoryClient) GetStreamId() uint32 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

// ReleaseTargets is the set of targets for a release operation.
type Args_ReleaseTargets struct {
	// The set of targets for a release. This is always guaranteed by
	// the caller to sum to 100%. If the release component doesn't support
	// traffic splitting, this is guaranteed to always be length 1.
	Targets              []*Args_ReleaseTargets_Target `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Args_ReleaseTargets) Reset()         { *m = Args_ReleaseTargets{} }
func (m *Args_ReleaseTargets) String() string { return proto.CompactTextString(m) }
func (*Args_ReleaseTargets) ProtoMessage()    {}
func (*Args_ReleaseTargets) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0, 6}
}
func (m *Args_ReleaseTargets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_ReleaseTargets.Unmarshal(m, b)
}
func (m *Args_ReleaseTargets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_ReleaseTargets.Marshal(b, m, deterministic)
}
func (dst *Args_ReleaseTargets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_ReleaseTargets.Merge(dst, src)
}
func (m *Args_ReleaseTargets) XXX_Size() int {
	return xxx_messageInfo_Args_ReleaseTargets.Size(m)
}
func (m *Args_ReleaseTargets) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_ReleaseTargets.DiscardUnknown(m)
}

var xxx_messageInfo_Args_ReleaseTargets proto.InternalMessageInfo

func (m *Args_ReleaseTargets) GetTargets() []*Args_ReleaseTargets_Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

// Target is a single target for releasing.
type Args_ReleaseTargets_Target struct {
	Deployment           *any.Any `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Percent              uint32   `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_ReleaseTargets_Target) Reset()         { *m = Args_ReleaseTargets_Target{} }
func (m *Args_ReleaseTargets_Target) String() string { return proto.CompactTextString(m) }
func (*Args_ReleaseTargets_Target) ProtoMessage()    {}
func (*Args_ReleaseTargets_Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{0, 6, 0}
}
func (m *Args_ReleaseTargets_Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_ReleaseTargets_Target.Unmarshal(m, b)
}
func (m *Args_ReleaseTargets_Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_ReleaseTargets_Target.Marshal(b, m, deterministic)
}
func (dst *Args_ReleaseTargets_Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_ReleaseTargets_Target.Merge(dst, src)
}
func (m *Args_ReleaseTargets_Target) XXX_Size() int {
	return xxx_messageInfo_Args_ReleaseTargets_Target.Size(m)
}
func (m *Args_ReleaseTargets_Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_ReleaseTargets_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Args_ReleaseTargets_Target proto.InternalMessageInfo

func (m *Args_ReleaseTargets_Target) GetDeployment() *any.Any {
	if m != nil {
		return m.Deployment
	}
	return nil
}

func (m *Args_ReleaseTargets_Target) GetPercent() uint32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

// Empty is just an empty message useful with some RPC endpoints.
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// FuncSpec describes a function and is used by the dependency-injection
// framework to provide the function with the proper values.
//
// Value types are specified using strings. Built-in framework types
// are defined via constants in the `sdk` package. For custom types, you
// can use whatever string as long as it is unique. We recommend using a
// unique prefix plus the Go type name.
type FuncSpec struct {
	// name of the function. This is used for improved logging.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// args is the list of arguments by protobuf Any types.
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// result is the resulting type. This is only critically important to be
	// set for functions that may chain to other functions. It can be set to
	// blank in which case it will not be used.
	Result               string   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuncSpec) Reset()         { *m = FuncSpec{} }
func (m *FuncSpec) String() string { return proto.CompactTextString(m) }
func (*FuncSpec) ProtoMessage()    {}
func (*FuncSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{2}
}
func (m *FuncSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncSpec.Unmarshal(m, b)
}
func (m *FuncSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncSpec.Marshal(b, m, deterministic)
}
func (dst *FuncSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncSpec.Merge(dst, src)
}
func (m *FuncSpec) XXX_Size() int {
	return xxx_messageInfo_FuncSpec.Size(m)
}
func (m *FuncSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncSpec.DiscardUnknown(m)
}

var xxx_messageInfo_FuncSpec proto.InternalMessageInfo

func (m *FuncSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FuncSpec) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *FuncSpec) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// Args is the standard argument type for an RPC that is calling a FuncSpec.
type FuncSpec_Args struct {
	// args is the list of argument types. This will include some of the
	// standard types in this file (in the Args message namespace) as well
	// as custom types declared by the FuncSpec that the plugin is expected
	// to understand how to decode.
	Args                 []*any.Any `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FuncSpec_Args) Reset()         { *m = FuncSpec_Args{} }
func (m *FuncSpec_Args) String() string { return proto.CompactTextString(m) }
func (*FuncSpec_Args) ProtoMessage()    {}
func (*FuncSpec_Args) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{2, 0}
}
func (m *FuncSpec_Args) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncSpec_Args.Unmarshal(m, b)
}
func (m *FuncSpec_Args) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncSpec_Args.Marshal(b, m, deterministic)
}
func (dst *FuncSpec_Args) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncSpec_Args.Merge(dst, src)
}
func (m *FuncSpec_Args) XXX_Size() int {
	return xxx_messageInfo_FuncSpec_Args.Size(m)
}
func (m *FuncSpec_Args) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncSpec_Args.DiscardUnknown(m)
}

var xxx_messageInfo_FuncSpec_Args proto.InternalMessageInfo

func (m *FuncSpec_Args) GetArgs() []*any.Any {
	if m != nil {
		return m.Args
	}
	return nil
}

// Config is the namespace of messages related to configuration.
//
// All components that take configuration are expected to have two RPC calls:
//
//   * ConfigStruct - Returns the configuration structure.
//   * Configure - Sends the configuration data back to the plugin and the
//       plugin is also expected to perform any validation at this stage.
//
type Config struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{3}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

// ConfigureRequest is the request sent once the configuration decoding
// is complete to actually assign the values to the structure.
type Config_ConfigureRequest struct {
	// json is the json data for the structure returned in the StructResp.
	// It is guaranteed to decode cleanly into the target structure.
	Json                 []byte   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config_ConfigureRequest) Reset()         { *m = Config_ConfigureRequest{} }
func (m *Config_ConfigureRequest) String() string { return proto.CompactTextString(m) }
func (*Config_ConfigureRequest) ProtoMessage()    {}
func (*Config_ConfigureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{3, 0}
}
func (m *Config_ConfigureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_ConfigureRequest.Unmarshal(m, b)
}
func (m *Config_ConfigureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_ConfigureRequest.Marshal(b, m, deterministic)
}
func (dst *Config_ConfigureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_ConfigureRequest.Merge(dst, src)
}
func (m *Config_ConfigureRequest) XXX_Size() int {
	return xxx_messageInfo_Config_ConfigureRequest.Size(m)
}
func (m *Config_ConfigureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_ConfigureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Config_ConfigureRequest proto.InternalMessageInfo

func (m *Config_ConfigureRequest) GetJson() []byte {
	if m != nil {
		return m.Json
	}
	return nil
}

// StructResp returns the struct for configuration.
type Config_StructResp struct {
	// struct is the configuration structure (or empty/nil if one doesn't exist).
	// This struct should have all the proper struct tags for HCL decoding
	// You should do validation on the Configure call.
	Struct               *protostructure.Struct `protobuf:"bytes,1,opt,name=struct,proto3" json:"struct,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Config_StructResp) Reset()         { *m = Config_StructResp{} }
func (m *Config_StructResp) String() string { return proto.CompactTextString(m) }
func (*Config_StructResp) ProtoMessage()    {}
func (*Config_StructResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{3, 1}
}
func (m *Config_StructResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_StructResp.Unmarshal(m, b)
}
func (m *Config_StructResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_StructResp.Marshal(b, m, deterministic)
}
func (dst *Config_StructResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_StructResp.Merge(dst, src)
}
func (m *Config_StructResp) XXX_Size() int {
	return xxx_messageInfo_Config_StructResp.Size(m)
}
func (m *Config_StructResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_StructResp.DiscardUnknown(m)
}

var xxx_messageInfo_Config_StructResp proto.InternalMessageInfo

func (m *Config_StructResp) GetStruct() *protostructure.Struct {
	if m != nil {
		return m.Struct
	}
	return nil
}

// ImplementsResp returns true if the component implements an additional interface.
type ImplementsResp struct {
	Implements           bool     `protobuf:"varint,1,opt,name=implements,proto3" json:"implements,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImplementsResp) Reset()         { *m = ImplementsResp{} }
func (m *ImplementsResp) String() string { return proto.CompactTextString(m) }
func (*ImplementsResp) ProtoMessage()    {}
func (*ImplementsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_45ea2bf8e3501311, []int{4}
}
func (m *ImplementsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImplementsResp.Unmarshal(m, b)
}
func (m *ImplementsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImplementsResp.Marshal(b, m, deterministic)
}
func (dst *ImplementsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImplementsResp.Merge(dst, src)
}
func (m *ImplementsResp) XXX_Size() int {
	return xxx_messageInfo_ImplementsResp.Size(m)
}
func (m *ImplementsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ImplementsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ImplementsResp proto.InternalMessageInfo

func (m *ImplementsResp) GetImplements() bool {
	if m != nil {
		return m.Implements
	}
	return false
}

func init() {
	proto.RegisterType((*Args)(nil), "proto.Args")
	proto.RegisterType((*Args_Source)(nil), "proto.Args.Source")
	proto.RegisterType((*Args_DeploymentConfig)(nil), "proto.Args.DeploymentConfig")
	proto.RegisterType((*Args_DataDir)(nil), "proto.Args.DataDir")
	proto.RegisterType((*Args_DataDir_Project)(nil), "proto.Args.DataDir.Project")
	proto.RegisterType((*Args_DataDir_App)(nil), "proto.Args.DataDir.App")
	proto.RegisterType((*Args_DataDir_Component)(nil), "proto.Args.DataDir.Component")
	proto.RegisterType((*Args_Logger)(nil), "proto.Args.Logger")
	proto.RegisterType((*Args_TerminalUI)(nil), "proto.Args.TerminalUI")
	proto.RegisterType((*Args_HistoryClient)(nil), "proto.Args.HistoryClient")
	proto.RegisterType((*Args_ReleaseTargets)(nil), "proto.Args.ReleaseTargets")
	proto.RegisterType((*Args_ReleaseTargets_Target)(nil), "proto.Args.ReleaseTargets.Target")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*FuncSpec)(nil), "proto.FuncSpec")
	proto.RegisterType((*FuncSpec_Args)(nil), "proto.FuncSpec.Args")
	proto.RegisterType((*Config)(nil), "proto.Config")
	proto.RegisterType((*Config_ConfigureRequest)(nil), "proto.Config.ConfigureRequest")
	proto.RegisterType((*Config_StructResp)(nil), "proto.Config.StructResp")
	proto.RegisterType((*ImplementsResp)(nil), "proto.ImplementsResp")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_plugin_45ea2bf8e3501311) }

var fileDescriptor_plugin_45ea2bf8e3501311 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x6e, 0x13, 0x3f,
	0x10, 0xc7, 0x95, 0xa6, 0xdd, 0xdd, 0x4e, 0xff, 0xfc, 0x22, 0xab, 0xaa, 0x52, 0xff, 0x10, 0x84,
	0x1c, 0x20, 0x07, 0xb4, 0xad, 0x0a, 0x37, 0xe0, 0x10, 0x25, 0x20, 0x22, 0x71, 0x40, 0x9b, 0x22,
	0x71, 0x40, 0x8a, 0xdc, 0xdd, 0xe9, 0x76, 0xab, 0x5d, 0xdb, 0x8c, 0xbd, 0x48, 0x91, 0x78, 0x1f,
	0x5e, 0x87, 0xf7, 0xe0, 0x25, 0xd0, 0xda, 0x4e, 0x55, 0x50, 0x4f, 0x3d, 0xf9, 0xeb, 0xcf, 0x7e,
	0x67, 0x3c, 0x3b, 0x1e, 0xc3, 0xbe, 0xae, 0xdb, 0xb2, 0x92, 0xa9, 0x26, 0x65, 0x15, 0xdb, 0x71,
	0x0b, 0x3f, 0x29, 0x95, 0x2a, 0x6b, 0x3c, 0x75, 0xbb, 0xcb, 0xf6, 0xea, 0x54, 0xc8, 0xb5, 0x77,
	0xf0, 0x23, 0xb7, 0x18, 0x4b, 0x6d, 0x6e, 0x5b, 0x42, 0x4f, 0xc7, 0xbf, 0xb7, 0x61, 0x7b, 0x4a,
	0xa5, 0xe1, 0x29, 0x44, 0x4b, 0xd5, 0x52, 0x8e, 0x6c, 0x00, 0x7d, 0xa1, 0xf5, 0xb0, 0x37, 0xea,
	0x4d, 0x76, 0xb3, 0x4e, 0x32, 0x06, 0xdb, 0x5a, 0xd8, 0xeb, 0xe1, 0x96, 0x43, 0x4e, 0xf3, 0xaf,
	0x30, 0x98, 0xa3, 0xae, 0xd5, 0xba, 0x41, 0x69, 0x67, 0x4a, 0x5e, 0x55, 0x25, 0x7b, 0x02, 0x7b,
	0x06, 0xe9, 0x3b, 0xd2, 0x4a, 0x14, 0x05, 0x85, 0x0c, 0xe0, 0xd1, 0xb4, 0x28, 0x88, 0x3d, 0x87,
	0xff, 0x82, 0xa1, 0x92, 0x06, 0xf3, 0x96, 0xd0, 0xe5, 0x4c, 0xb2, 0x43, 0x8f, 0x17, 0x81, 0xf2,
	0x5f, 0x3d, 0x88, 0xe7, 0xc2, 0x8a, 0x79, 0x45, 0x7c, 0x0a, 0xf1, 0x27, 0x52, 0x37, 0x98, 0x5b,
	0xf6, 0x3f, 0xec, 0xe6, 0x22, 0xbf, 0xc6, 0x55, 0x51, 0x51, 0xa8, 0x26, 0x71, 0x60, 0x5e, 0x11,
	0x3b, 0x81, 0xa4, 0x10, 0x56, 0xb8, 0x6f, 0x7d, 0xf7, 0x2d, 0x2e, 0x42, 0x8a, 0xb7, 0xd0, 0x9f,
	0x6a, 0xfd, 0xe0, 0xf0, 0x19, 0xec, 0xce, 0x54, 0xa3, 0x95, 0x44, 0xf9, 0xf0, 0x1a, 0x1e, 0x41,
	0xf4, 0x51, 0x95, 0x25, 0x52, 0xd7, 0x4e, 0x29, 0x1a, 0x0c, 0xfd, 0x71, 0x9a, 0xef, 0x03, 0x5c,
	0x20, 0x35, 0x95, 0x14, 0xf5, 0xe7, 0x05, 0x7f, 0x01, 0x07, 0x1f, 0x2a, 0x63, 0x15, 0xad, 0x67,
	0x75, 0x15, 0x0e, 0x35, 0x96, 0x50, 0x34, 0xab, 0xaa, 0x70, 0x71, 0x07, 0x59, 0xe2, 0xc1, 0xa2,
	0xe0, 0x3f, 0x7b, 0x70, 0x98, 0x61, 0x8d, 0xc2, 0xe0, 0x85, 0xa0, 0x12, 0xad, 0x61, 0xaf, 0x21,
	0xb6, 0x5e, 0x0e, 0x7b, 0xa3, 0xfe, 0x64, 0xef, 0xfc, 0xa9, 0xbf, 0xef, 0xb4, 0xbb, 0xeb, 0xf4,
	0x6f, 0x73, 0xea, 0xd7, 0x6c, 0x13, 0xc1, 0xbf, 0x40, 0xe4, 0x11, 0x7b, 0x05, 0x50, 0xdc, 0x5e,
	0xb2, 0x3b, 0x77, 0xef, 0xfc, 0x28, 0xf5, 0x33, 0x96, 0x6e, 0x66, 0x2c, 0x9d, 0xca, 0x75, 0x76,
	0xc7, 0xc7, 0x86, 0x10, 0x6b, 0xa4, 0xbc, 0x0b, 0xd9, 0x72, 0xa5, 0x6e, 0xb6, 0xe3, 0x18, 0x76,
	0xde, 0x35, 0xda, 0xae, 0xc7, 0x3f, 0x20, 0x79, 0xdf, 0xca, 0x7c, 0xa9, 0x31, 0xbf, 0xaf, 0x1d,
	0x1d, 0x13, 0x54, 0x9a, 0xe1, 0xd6, 0xa8, 0xdf, 0xb1, 0x4e, 0xb3, 0x63, 0x88, 0x08, 0x4d, 0x5b,
	0xdb, 0xd0, 0xd9, 0xb0, 0xe3, 0x67, 0x7e, 0x82, 0xd9, 0x24, 0xc4, 0xf8, 0x1f, 0xbe, 0xbf, 0x4c,
	0xe7, 0x18, 0x4b, 0x88, 0xfc, 0xc4, 0xf2, 0x67, 0x30, 0xf0, 0xaa, 0x25, 0xcc, 0xf0, 0x5b, 0x8b,
	0xc6, 0x76, 0x67, 0xdf, 0x18, 0x25, 0x5d, 0x3d, 0xfb, 0x99, 0xd3, 0xfc, 0x0d, 0xc0, 0xd2, 0xbd,
	0x9c, 0x0c, 0x8d, 0x66, 0x29, 0x44, 0xfe, 0x1d, 0x85, 0x96, 0x1c, 0xa7, 0xff, 0xbc, 0xad, 0xe0,
	0x0d, 0xae, 0xf1, 0x19, 0x1c, 0x2e, 0x1a, 0x5d, 0x63, 0xd7, 0x1d, 0xe3, 0x32, 0x3c, 0x06, 0xa8,
	0x6e, 0x89, 0xcb, 0x92, 0x64, 0x77, 0xc8, 0x65, 0xe4, 0x12, 0xbe, 0xfc, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xda, 0x92, 0x4d, 0x41, 0xe5, 0x03, 0x00, 0x00,
}
