// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Args are the common argument types that are available to many of the
// dynamic functions. The exact list of available argument types is available
// on the Go interface docs.
type Args struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args) Reset()         { *m = Args{} }
func (m *Args) String() string { return proto.CompactTextString(m) }
func (*Args) ProtoMessage()    {}
func (*Args) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_48714e86091d61be, []int{0}
}
func (m *Args) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args.Unmarshal(m, b)
}
func (m *Args) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args.Marshal(b, m, deterministic)
}
func (dst *Args) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args.Merge(dst, src)
}
func (m *Args) XXX_Size() int {
	return xxx_messageInfo_Args.Size(m)
}
func (m *Args) XXX_DiscardUnknown() {
	xxx_messageInfo_Args.DiscardUnknown(m)
}

var xxx_messageInfo_Args proto.InternalMessageInfo

// See component.Source
type Args_Source struct {
	// app is the name of the application being deployed.
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// path is the absolute directory path to the root directory for source files.
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_Source) Reset()         { *m = Args_Source{} }
func (m *Args_Source) String() string { return proto.CompactTextString(m) }
func (*Args_Source) ProtoMessage()    {}
func (*Args_Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_48714e86091d61be, []int{0, 0}
}
func (m *Args_Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_Source.Unmarshal(m, b)
}
func (m *Args_Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_Source.Marshal(b, m, deterministic)
}
func (dst *Args_Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_Source.Merge(dst, src)
}
func (m *Args_Source) XXX_Size() int {
	return xxx_messageInfo_Args_Source.Size(m)
}
func (m *Args_Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Args_Source proto.InternalMessageInfo

func (m *Args_Source) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Args_Source) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// DataDir represents the directory where data can be stored. This is an internal
// struct and shouldn't be used directly. Use the relevant *datadir implementation
// instead.
type Args_DataDir struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_DataDir) Reset()         { *m = Args_DataDir{} }
func (m *Args_DataDir) String() string { return proto.CompactTextString(m) }
func (*Args_DataDir) ProtoMessage()    {}
func (*Args_DataDir) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_48714e86091d61be, []int{0, 1}
}
func (m *Args_DataDir) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_DataDir.Unmarshal(m, b)
}
func (m *Args_DataDir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_DataDir.Marshal(b, m, deterministic)
}
func (dst *Args_DataDir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_DataDir.Merge(dst, src)
}
func (m *Args_DataDir) XXX_Size() int {
	return xxx_messageInfo_Args_DataDir.Size(m)
}
func (m *Args_DataDir) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_DataDir.DiscardUnknown(m)
}

var xxx_messageInfo_Args_DataDir proto.InternalMessageInfo

type Args_DataDir_Project struct {
	CacheDir             string   `protobuf:"bytes,2,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	DataDir              string   `protobuf:"bytes,3,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_DataDir_Project) Reset()         { *m = Args_DataDir_Project{} }
func (m *Args_DataDir_Project) String() string { return proto.CompactTextString(m) }
func (*Args_DataDir_Project) ProtoMessage()    {}
func (*Args_DataDir_Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_48714e86091d61be, []int{0, 1, 0}
}
func (m *Args_DataDir_Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_DataDir_Project.Unmarshal(m, b)
}
func (m *Args_DataDir_Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_DataDir_Project.Marshal(b, m, deterministic)
}
func (dst *Args_DataDir_Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_DataDir_Project.Merge(dst, src)
}
func (m *Args_DataDir_Project) XXX_Size() int {
	return xxx_messageInfo_Args_DataDir_Project.Size(m)
}
func (m *Args_DataDir_Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_DataDir_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Args_DataDir_Project proto.InternalMessageInfo

func (m *Args_DataDir_Project) GetCacheDir() string {
	if m != nil {
		return m.CacheDir
	}
	return ""
}

func (m *Args_DataDir_Project) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

type Args_DataDir_App struct {
	CacheDir             string   `protobuf:"bytes,2,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	DataDir              string   `protobuf:"bytes,3,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_DataDir_App) Reset()         { *m = Args_DataDir_App{} }
func (m *Args_DataDir_App) String() string { return proto.CompactTextString(m) }
func (*Args_DataDir_App) ProtoMessage()    {}
func (*Args_DataDir_App) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_48714e86091d61be, []int{0, 1, 1}
}
func (m *Args_DataDir_App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_DataDir_App.Unmarshal(m, b)
}
func (m *Args_DataDir_App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_DataDir_App.Marshal(b, m, deterministic)
}
func (dst *Args_DataDir_App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_DataDir_App.Merge(dst, src)
}
func (m *Args_DataDir_App) XXX_Size() int {
	return xxx_messageInfo_Args_DataDir_App.Size(m)
}
func (m *Args_DataDir_App) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_DataDir_App.DiscardUnknown(m)
}

var xxx_messageInfo_Args_DataDir_App proto.InternalMessageInfo

func (m *Args_DataDir_App) GetCacheDir() string {
	if m != nil {
		return m.CacheDir
	}
	return ""
}

func (m *Args_DataDir_App) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

type Args_DataDir_Component struct {
	CacheDir             string   `protobuf:"bytes,2,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	DataDir              string   `protobuf:"bytes,3,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args_DataDir_Component) Reset()         { *m = Args_DataDir_Component{} }
func (m *Args_DataDir_Component) String() string { return proto.CompactTextString(m) }
func (*Args_DataDir_Component) ProtoMessage()    {}
func (*Args_DataDir_Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_48714e86091d61be, []int{0, 1, 2}
}
func (m *Args_DataDir_Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args_DataDir_Component.Unmarshal(m, b)
}
func (m *Args_DataDir_Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args_DataDir_Component.Marshal(b, m, deterministic)
}
func (dst *Args_DataDir_Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args_DataDir_Component.Merge(dst, src)
}
func (m *Args_DataDir_Component) XXX_Size() int {
	return xxx_messageInfo_Args_DataDir_Component.Size(m)
}
func (m *Args_DataDir_Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Args_DataDir_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Args_DataDir_Component proto.InternalMessageInfo

func (m *Args_DataDir_Component) GetCacheDir() string {
	if m != nil {
		return m.CacheDir
	}
	return ""
}

func (m *Args_DataDir_Component) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

// Empty is just an empty message useful with some RPC endpoints.
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_48714e86091d61be, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// FuncSpec describes a function and is used by the dependency-injection
// framework to provide the function with the proper values.
//
// Value types are specified using strings. Built-in framework types
// are defined via constants in the `sdk` package. For custom types, you
// can use whatever string as long as it is unique. We recommend using a
// unique prefix plus the Go type name.
type FuncSpec struct {
	Args                 []string `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuncSpec) Reset()         { *m = FuncSpec{} }
func (m *FuncSpec) String() string { return proto.CompactTextString(m) }
func (*FuncSpec) ProtoMessage()    {}
func (*FuncSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_48714e86091d61be, []int{2}
}
func (m *FuncSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncSpec.Unmarshal(m, b)
}
func (m *FuncSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncSpec.Marshal(b, m, deterministic)
}
func (dst *FuncSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncSpec.Merge(dst, src)
}
func (m *FuncSpec) XXX_Size() int {
	return xxx_messageInfo_FuncSpec.Size(m)
}
func (m *FuncSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncSpec.DiscardUnknown(m)
}

var xxx_messageInfo_FuncSpec proto.InternalMessageInfo

func (m *FuncSpec) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *FuncSpec) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Args)(nil), "proto.Args")
	proto.RegisterType((*Args_Source)(nil), "proto.Args.Source")
	proto.RegisterType((*Args_DataDir)(nil), "proto.Args.DataDir")
	proto.RegisterType((*Args_DataDir_Project)(nil), "proto.Args.DataDir.Project")
	proto.RegisterType((*Args_DataDir_App)(nil), "proto.Args.DataDir.App")
	proto.RegisterType((*Args_DataDir_Component)(nil), "proto.Args.DataDir.Component")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*FuncSpec)(nil), "proto.FuncSpec")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_plugin_48714e86091d61be) }

var fileDescriptor_plugin_48714e86091d61be = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x55, 0x9a, 0x36, 0x4e, 0x4e, 0x0c, 0xc8, 0x03, 0x0a, 0x61, 0xa9, 0x32, 0x31, 0x75, 0x41,
	0x62, 0x63, 0x88, 0x1a, 0x98, 0x11, 0xfd, 0x00, 0x74, 0x38, 0x56, 0x6a, 0xd4, 0xda, 0xa7, 0x8b,
	0x3d, 0xf0, 0x09, 0xfc, 0x1d, 0x9f, 0x84, 0x6c, 0xf9, 0x0b, 0x32, 0xdd, 0xbb, 0xf7, 0xee, 0x9e,
	0xee, 0x1d, 0xdc, 0xd0, 0x25, 0xcc, 0xc6, 0x1e, 0x88, 0x9d, 0x77, 0x72, 0x97, 0x4a, 0xff, 0xbb,
	0x81, 0xed, 0xc0, 0xf3, 0xd2, 0x1d, 0xa0, 0x3a, 0xb9, 0xc0, 0x4a, 0xcb, 0x5b, 0x28, 0x91, 0xa8,
	0x2d, 0xf6, 0xc5, 0x63, 0xf3, 0x11, 0xa1, 0x94, 0xb0, 0x25, 0xf4, 0xe7, 0x76, 0x93, 0xa8, 0x84,
	0xbb, 0xbf, 0x02, 0xc4, 0x88, 0x1e, 0x47, 0xc3, 0xdd, 0x00, 0xe2, 0x9d, 0xdd, 0xb7, 0x56, 0x5e,
	0x3e, 0x40, 0xa3, 0x50, 0x9d, 0xf5, 0xe7, 0x64, 0x38, 0xcf, 0xd7, 0x89, 0x18, 0x0d, 0xcb, 0x7b,
	0xa8, 0x27, 0xf4, 0x98, 0xb4, 0x32, 0x69, 0x62, 0xca, 0x16, 0x2f, 0x50, 0x0e, 0x44, 0xab, 0xd7,
	0x8f, 0xd0, 0x1c, 0xdd, 0x95, 0x9c, 0xd5, 0x76, 0xf5, 0x0d, 0xbd, 0x80, 0xdd, 0xeb, 0x95, 0xfc,
	0x4f, 0xff, 0x0c, 0xf5, 0x5b, 0xb0, 0xea, 0x44, 0x5a, 0xc5, 0xec, 0xc8, 0xf3, 0xd2, 0x16, 0xfb,
	0x32, 0x66, 0x8f, 0x58, 0xde, 0x41, 0xc5, 0x7a, 0x09, 0x17, 0x9f, 0xdd, 0x73, 0xf7, 0x55, 0xa5,
	0x9f, 0x3e, 0xfd, 0x07, 0x00, 0x00, 0xff, 0xff, 0x96, 0x82, 0xae, 0x9c, 0x6a, 0x01, 0x00, 0x00,
}
