// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Push struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Push) Reset()         { *m = Push{} }
func (m *Push) String() string { return proto.CompactTextString(m) }
func (*Push) ProtoMessage()    {}
func (*Push) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_ed8247945789a254, []int{0}
}
func (m *Push) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Push.Unmarshal(m, b)
}
func (m *Push) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Push.Marshal(b, m, deterministic)
}
func (dst *Push) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Push.Merge(dst, src)
}
func (m *Push) XXX_Size() int {
	return xxx_messageInfo_Push.Size(m)
}
func (m *Push) XXX_DiscardUnknown() {
	xxx_messageInfo_Push.DiscardUnknown(m)
}

var xxx_messageInfo_Push proto.InternalMessageInfo

type Push_Args struct {
	// args is the list of argument types. This will include some of the
	// standard types in this file (in the Args message namespace) as well
	// as custom types declared by the FuncSpec that the plugin is expected
	// to understand how to decode.
	Args                 []*any.Any `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Push_Args) Reset()         { *m = Push_Args{} }
func (m *Push_Args) String() string { return proto.CompactTextString(m) }
func (*Push_Args) ProtoMessage()    {}
func (*Push_Args) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_ed8247945789a254, []int{0, 0}
}
func (m *Push_Args) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Push_Args.Unmarshal(m, b)
}
func (m *Push_Args) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Push_Args.Marshal(b, m, deterministic)
}
func (dst *Push_Args) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Push_Args.Merge(dst, src)
}
func (m *Push_Args) XXX_Size() int {
	return xxx_messageInfo_Push_Args.Size(m)
}
func (m *Push_Args) XXX_DiscardUnknown() {
	xxx_messageInfo_Push_Args.DiscardUnknown(m)
}

var xxx_messageInfo_Push_Args proto.InternalMessageInfo

func (m *Push_Args) GetArgs() []*any.Any {
	if m != nil {
		return m.Args
	}
	return nil
}

type Push_Resp struct {
	// result is the resulting opaque data type
	Result               *any.Any `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Push_Resp) Reset()         { *m = Push_Resp{} }
func (m *Push_Resp) String() string { return proto.CompactTextString(m) }
func (*Push_Resp) ProtoMessage()    {}
func (*Push_Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_ed8247945789a254, []int{0, 1}
}
func (m *Push_Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Push_Resp.Unmarshal(m, b)
}
func (m *Push_Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Push_Resp.Marshal(b, m, deterministic)
}
func (dst *Push_Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Push_Resp.Merge(dst, src)
}
func (m *Push_Resp) XXX_Size() int {
	return xxx_messageInfo_Push_Resp.Size(m)
}
func (m *Push_Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Push_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Push_Resp proto.InternalMessageInfo

func (m *Push_Resp) GetResult() *any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Push)(nil), "proto.Push")
	proto.RegisterType((*Push_Args)(nil), "proto.Push.Args")
	proto.RegisterType((*Push_Resp)(nil), "proto.Push.Resp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryClient interface {
	PushSpec(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FuncSpec, error)
	Push(ctx context.Context, in *Push_Args, opts ...grpc.CallOption) (*Push_Resp, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) PushSpec(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FuncSpec, error) {
	out := new(FuncSpec)
	err := c.cc.Invoke(ctx, "/proto.Registry/PushSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) Push(ctx context.Context, in *Push_Args, opts ...grpc.CallOption) (*Push_Resp, error) {
	out := new(Push_Resp)
	err := c.cc.Invoke(ctx, "/proto.Registry/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
type RegistryServer interface {
	PushSpec(context.Context, *Empty) (*FuncSpec, error)
	Push(context.Context, *Push_Args) (*Push_Resp, error)
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_PushSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).PushSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Registry/PushSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).PushSpec(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Push_Args)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Registry/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).Push(ctx, req.(*Push_Args))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushSpec",
			Handler:    _Registry_PushSpec_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _Registry_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_registry_ed8247945789a254) }

var fileDescriptor_registry_ed8247945789a254 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x4d, 0xcf,
	0x2c, 0x2e, 0x29, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x92,
	0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x5e, 0x52, 0x69, 0x9a, 0x7e, 0x62, 0x1e, 0x54,
	0x85, 0x14, 0x4f, 0x41, 0x4e, 0x69, 0x7a, 0x66, 0x1e, 0x84, 0xa7, 0x94, 0xc7, 0xc5, 0x12, 0x50,
	0x5a, 0x9c, 0x21, 0x65, 0xc0, 0xc5, 0xe2, 0x58, 0x94, 0x5e, 0x2c, 0xa4, 0xc1, 0xc5, 0x92, 0x58,
	0x94, 0x5e, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa2, 0x07, 0x31, 0x47, 0x0f, 0x66,
	0x8e, 0x9e, 0x63, 0x5e, 0x65, 0x10, 0x58, 0x85, 0x94, 0x09, 0x17, 0x4b, 0x50, 0x6a, 0x71, 0x81,
	0x90, 0x0e, 0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e, 0x89, 0x04, 0xa3, 0x02, 0x23, 0x4e, 0x3d,
	0x50, 0x35, 0x46, 0x89, 0x5c, 0x1c, 0x41, 0x50, 0x17, 0x0b, 0x69, 0x72, 0x71, 0x80, 0xec, 0x0e,
	0x2e, 0x48, 0x4d, 0x16, 0xe2, 0x81, 0x28, 0xd7, 0x73, 0xcd, 0x2d, 0x28, 0xa9, 0x94, 0xe2, 0x87,
	0xf2, 0xdc, 0x4a, 0xf3, 0x92, 0xc1, 0xd2, 0x5a, 0x10, 0x67, 0x0a, 0x09, 0x40, 0x25, 0x40, 0x1c,
	0x3d, 0x90, 0x83, 0xa5, 0x50, 0x44, 0x40, 0x0e, 0x4a, 0x62, 0x03, 0x0b, 0x18, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xb8, 0x4d, 0x74, 0x29, 0x1b, 0x01, 0x00, 0x00,
}
