// Code generated by protoc-gen-go. DO NOT EDIT.
// source: terminal.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TerminalUI struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminalUI) Reset()         { *m = TerminalUI{} }
func (m *TerminalUI) String() string { return proto.CompactTextString(m) }
func (*TerminalUI) ProtoMessage()    {}
func (*TerminalUI) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8b8260c8ef16ad, []int{0}
}

func (m *TerminalUI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalUI.Unmarshal(m, b)
}
func (m *TerminalUI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalUI.Marshal(b, m, deterministic)
}
func (m *TerminalUI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalUI.Merge(m, src)
}
func (m *TerminalUI) XXX_Size() int {
	return xxx_messageInfo_TerminalUI.Size(m)
}
func (m *TerminalUI) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalUI.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalUI proto.InternalMessageInfo

type TerminalUI_OutputRequest struct {
	Lines                []string `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminalUI_OutputRequest) Reset()         { *m = TerminalUI_OutputRequest{} }
func (m *TerminalUI_OutputRequest) String() string { return proto.CompactTextString(m) }
func (*TerminalUI_OutputRequest) ProtoMessage()    {}
func (*TerminalUI_OutputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8b8260c8ef16ad, []int{0, 0}
}

func (m *TerminalUI_OutputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalUI_OutputRequest.Unmarshal(m, b)
}
func (m *TerminalUI_OutputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalUI_OutputRequest.Marshal(b, m, deterministic)
}
func (m *TerminalUI_OutputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalUI_OutputRequest.Merge(m, src)
}
func (m *TerminalUI_OutputRequest) XXX_Size() int {
	return xxx_messageInfo_TerminalUI_OutputRequest.Size(m)
}
func (m *TerminalUI_OutputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalUI_OutputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalUI_OutputRequest proto.InternalMessageInfo

func (m *TerminalUI_OutputRequest) GetLines() []string {
	if m != nil {
		return m.Lines
	}
	return nil
}

type TerminalUI_Event struct {
	// Types that are valid to be assigned to Event:
	//	*TerminalUI_Event_Line_
	//	*TerminalUI_Event_Status_
	//	*TerminalUI_Event_Table_
	//	*TerminalUI_Event_Raw_
	Event                isTerminalUI_Event_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TerminalUI_Event) Reset()         { *m = TerminalUI_Event{} }
func (m *TerminalUI_Event) String() string { return proto.CompactTextString(m) }
func (*TerminalUI_Event) ProtoMessage()    {}
func (*TerminalUI_Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8b8260c8ef16ad, []int{0, 1}
}

func (m *TerminalUI_Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalUI_Event.Unmarshal(m, b)
}
func (m *TerminalUI_Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalUI_Event.Marshal(b, m, deterministic)
}
func (m *TerminalUI_Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalUI_Event.Merge(m, src)
}
func (m *TerminalUI_Event) XXX_Size() int {
	return xxx_messageInfo_TerminalUI_Event.Size(m)
}
func (m *TerminalUI_Event) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalUI_Event.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalUI_Event proto.InternalMessageInfo

type isTerminalUI_Event_Event interface {
	isTerminalUI_Event_Event()
}

type TerminalUI_Event_Line_ struct {
	Line *TerminalUI_Event_Line `protobuf:"bytes,1,opt,name=line,proto3,oneof"`
}

type TerminalUI_Event_Status_ struct {
	Status *TerminalUI_Event_Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

type TerminalUI_Event_Table_ struct {
	Table *TerminalUI_Event_Table `protobuf:"bytes,3,opt,name=table,proto3,oneof"`
}

type TerminalUI_Event_Raw_ struct {
	Raw *TerminalUI_Event_Raw `protobuf:"bytes,4,opt,name=raw,proto3,oneof"`
}

func (*TerminalUI_Event_Line_) isTerminalUI_Event_Event() {}

func (*TerminalUI_Event_Status_) isTerminalUI_Event_Event() {}

func (*TerminalUI_Event_Table_) isTerminalUI_Event_Event() {}

func (*TerminalUI_Event_Raw_) isTerminalUI_Event_Event() {}

func (m *TerminalUI_Event) GetEvent() isTerminalUI_Event_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *TerminalUI_Event) GetLine() *TerminalUI_Event_Line {
	if x, ok := m.GetEvent().(*TerminalUI_Event_Line_); ok {
		return x.Line
	}
	return nil
}

func (m *TerminalUI_Event) GetStatus() *TerminalUI_Event_Status {
	if x, ok := m.GetEvent().(*TerminalUI_Event_Status_); ok {
		return x.Status
	}
	return nil
}

func (m *TerminalUI_Event) GetTable() *TerminalUI_Event_Table {
	if x, ok := m.GetEvent().(*TerminalUI_Event_Table_); ok {
		return x.Table
	}
	return nil
}

func (m *TerminalUI_Event) GetRaw() *TerminalUI_Event_Raw {
	if x, ok := m.GetEvent().(*TerminalUI_Event_Raw_); ok {
		return x.Raw
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TerminalUI_Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TerminalUI_Event_Line_)(nil),
		(*TerminalUI_Event_Status_)(nil),
		(*TerminalUI_Event_Table_)(nil),
		(*TerminalUI_Event_Raw_)(nil),
	}
}

type TerminalUI_Event_Status struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Step                 bool     `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminalUI_Event_Status) Reset()         { *m = TerminalUI_Event_Status{} }
func (m *TerminalUI_Event_Status) String() string { return proto.CompactTextString(m) }
func (*TerminalUI_Event_Status) ProtoMessage()    {}
func (*TerminalUI_Event_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8b8260c8ef16ad, []int{0, 1, 0}
}

func (m *TerminalUI_Event_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalUI_Event_Status.Unmarshal(m, b)
}
func (m *TerminalUI_Event_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalUI_Event_Status.Marshal(b, m, deterministic)
}
func (m *TerminalUI_Event_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalUI_Event_Status.Merge(m, src)
}
func (m *TerminalUI_Event_Status) XXX_Size() int {
	return xxx_messageInfo_TerminalUI_Event_Status.Size(m)
}
func (m *TerminalUI_Event_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalUI_Event_Status.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalUI_Event_Status proto.InternalMessageInfo

func (m *TerminalUI_Event_Status) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TerminalUI_Event_Status) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *TerminalUI_Event_Status) GetStep() bool {
	if m != nil {
		return m.Step
	}
	return false
}

type TerminalUI_Event_Line struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Style                string   `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminalUI_Event_Line) Reset()         { *m = TerminalUI_Event_Line{} }
func (m *TerminalUI_Event_Line) String() string { return proto.CompactTextString(m) }
func (*TerminalUI_Event_Line) ProtoMessage()    {}
func (*TerminalUI_Event_Line) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8b8260c8ef16ad, []int{0, 1, 1}
}

func (m *TerminalUI_Event_Line) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalUI_Event_Line.Unmarshal(m, b)
}
func (m *TerminalUI_Event_Line) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalUI_Event_Line.Marshal(b, m, deterministic)
}
func (m *TerminalUI_Event_Line) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalUI_Event_Line.Merge(m, src)
}
func (m *TerminalUI_Event_Line) XXX_Size() int {
	return xxx_messageInfo_TerminalUI_Event_Line.Size(m)
}
func (m *TerminalUI_Event_Line) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalUI_Event_Line.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalUI_Event_Line proto.InternalMessageInfo

func (m *TerminalUI_Event_Line) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *TerminalUI_Event_Line) GetStyle() string {
	if m != nil {
		return m.Style
	}
	return ""
}

type TerminalUI_Event_Raw struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Stderr               bool     `protobuf:"varint,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminalUI_Event_Raw) Reset()         { *m = TerminalUI_Event_Raw{} }
func (m *TerminalUI_Event_Raw) String() string { return proto.CompactTextString(m) }
func (*TerminalUI_Event_Raw) ProtoMessage()    {}
func (*TerminalUI_Event_Raw) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8b8260c8ef16ad, []int{0, 1, 2}
}

func (m *TerminalUI_Event_Raw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalUI_Event_Raw.Unmarshal(m, b)
}
func (m *TerminalUI_Event_Raw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalUI_Event_Raw.Marshal(b, m, deterministic)
}
func (m *TerminalUI_Event_Raw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalUI_Event_Raw.Merge(m, src)
}
func (m *TerminalUI_Event_Raw) XXX_Size() int {
	return xxx_messageInfo_TerminalUI_Event_Raw.Size(m)
}
func (m *TerminalUI_Event_Raw) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalUI_Event_Raw.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalUI_Event_Raw proto.InternalMessageInfo

func (m *TerminalUI_Event_Raw) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TerminalUI_Event_Raw) GetStderr() bool {
	if m != nil {
		return m.Stderr
	}
	return false
}

type TerminalUI_Event_TableRow struct {
	Columns              []string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminalUI_Event_TableRow) Reset()         { *m = TerminalUI_Event_TableRow{} }
func (m *TerminalUI_Event_TableRow) String() string { return proto.CompactTextString(m) }
func (*TerminalUI_Event_TableRow) ProtoMessage()    {}
func (*TerminalUI_Event_TableRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8b8260c8ef16ad, []int{0, 1, 3}
}

func (m *TerminalUI_Event_TableRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalUI_Event_TableRow.Unmarshal(m, b)
}
func (m *TerminalUI_Event_TableRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalUI_Event_TableRow.Marshal(b, m, deterministic)
}
func (m *TerminalUI_Event_TableRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalUI_Event_TableRow.Merge(m, src)
}
func (m *TerminalUI_Event_TableRow) XXX_Size() int {
	return xxx_messageInfo_TerminalUI_Event_TableRow.Size(m)
}
func (m *TerminalUI_Event_TableRow) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalUI_Event_TableRow.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalUI_Event_TableRow proto.InternalMessageInfo

func (m *TerminalUI_Event_TableRow) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

type TerminalUI_Event_Table struct {
	Rows                 []*TerminalUI_Event_TableRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TerminalUI_Event_Table) Reset()         { *m = TerminalUI_Event_Table{} }
func (m *TerminalUI_Event_Table) String() string { return proto.CompactTextString(m) }
func (*TerminalUI_Event_Table) ProtoMessage()    {}
func (*TerminalUI_Event_Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8b8260c8ef16ad, []int{0, 1, 4}
}

func (m *TerminalUI_Event_Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalUI_Event_Table.Unmarshal(m, b)
}
func (m *TerminalUI_Event_Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalUI_Event_Table.Marshal(b, m, deterministic)
}
func (m *TerminalUI_Event_Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalUI_Event_Table.Merge(m, src)
}
func (m *TerminalUI_Event_Table) XXX_Size() int {
	return xxx_messageInfo_TerminalUI_Event_Table.Size(m)
}
func (m *TerminalUI_Event_Table) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalUI_Event_Table.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalUI_Event_Table proto.InternalMessageInfo

func (m *TerminalUI_Event_Table) GetRows() []*TerminalUI_Event_TableRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*TerminalUI)(nil), "proto.TerminalUI")
	proto.RegisterType((*TerminalUI_OutputRequest)(nil), "proto.TerminalUI.OutputRequest")
	proto.RegisterType((*TerminalUI_Event)(nil), "proto.TerminalUI.Event")
	proto.RegisterType((*TerminalUI_Event_Status)(nil), "proto.TerminalUI.Event.Status")
	proto.RegisterType((*TerminalUI_Event_Line)(nil), "proto.TerminalUI.Event.Line")
	proto.RegisterType((*TerminalUI_Event_Raw)(nil), "proto.TerminalUI.Event.Raw")
	proto.RegisterType((*TerminalUI_Event_TableRow)(nil), "proto.TerminalUI.Event.TableRow")
	proto.RegisterType((*TerminalUI_Event_Table)(nil), "proto.TerminalUI.Event.Table")
}

func init() {
	proto.RegisterFile("terminal.proto", fileDescriptor_ff8b8260c8ef16ad)
}

var fileDescriptor_ff8b8260c8ef16ad = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x13, 0xf3, 0x67, 0xdb, 0xb3, 0x2a, 0x3a, 0x2c, 0x6b, 0x98, 0xf5, 0x4f, 0x11, 0x85,
	0x5e, 0x4d, 0x31, 0x2a, 0x08, 0xe2, 0x85, 0x42, 0x25, 0x82, 0x20, 0x4c, 0xeb, 0x03, 0x4c, 0xdb,
	0xb1, 0x04, 0x92, 0x4c, 0xcc, 0x4c, 0x1a, 0xfa, 0x1c, 0xbe, 0x86, 0xcf, 0xe7, 0xb5, 0xcc, 0x99,
	0xa4, 0x45, 0x24, 0x7b, 0x95, 0x39, 0x27, 0xbf, 0xef, 0xcc, 0x77, 0x92, 0x0f, 0xee, 0x1b, 0xd9,
	0x94, 0x79, 0x25, 0x0a, 0x56, 0x37, 0xca, 0x28, 0x12, 0xe1, 0x83, 0xde, 0xec, 0x95, 0xda, 0x17,
	0x72, 0x81, 0xd5, 0xa6, 0xfd, 0xb1, 0x90, 0x65, 0x6d, 0x8e, 0x8e, 0x79, 0xfe, 0x3b, 0x04, 0x58,
	0xf7, 0xb2, 0xef, 0x5f, 0xe8, 0x4b, 0xb8, 0xf7, 0xad, 0x35, 0x75, 0x6b, 0xb8, 0xfc, 0xd9, 0x4a,
	0x6d, 0xc8, 0x15, 0x44, 0x45, 0x5e, 0x49, 0x9d, 0xf8, 0xb3, 0x60, 0x3e, 0xe5, 0xae, 0xa0, 0x7f,
	0x02, 0x88, 0x96, 0x07, 0x59, 0x19, 0x92, 0x42, 0x68, 0x5b, 0x89, 0x3f, 0xf3, 0xe7, 0x97, 0xe9,
	0x63, 0x37, 0x95, 0x9d, 0x27, 0x32, 0xc4, 0xd8, 0xd7, 0xbc, 0x92, 0x99, 0xc7, 0x91, 0x25, 0xef,
	0x20, 0xd6, 0x46, 0x98, 0x56, 0x27, 0x77, 0x50, 0xf5, 0x74, 0x4c, 0xb5, 0x42, 0x2a, 0xf3, 0x78,
	0xcf, 0x93, 0xb7, 0x10, 0x19, 0xb1, 0x29, 0x64, 0x12, 0xa0, 0xf0, 0xc9, 0x98, 0x70, 0x6d, 0xa1,
	0xcc, 0xe3, 0x8e, 0x26, 0x0b, 0x08, 0x1a, 0xd1, 0x25, 0x21, 0x8a, 0x6e, 0xc6, 0x44, 0x5c, 0x74,
	0x99, 0xc7, 0x2d, 0x49, 0x3f, 0x43, 0xec, 0xee, 0x26, 0xd7, 0x27, 0xaf, 0x76, 0xc3, 0xe9, 0xc9,
	0xc9, 0x03, 0x08, 0x4a, 0xbd, 0xc7, 0x05, 0xa6, 0xdc, 0x1e, 0x09, 0x81, 0x50, 0x1b, 0x59, 0xa3,
	0xb5, 0x09, 0xc7, 0x33, 0x65, 0x10, 0xda, 0xcd, 0x07, 0xda, 0x3f, 0xd3, 0x57, 0x10, 0x69, 0x73,
	0x2c, 0x64, 0x3f, 0xc1, 0x15, 0xf4, 0x15, 0x04, 0x5c, 0x74, 0x76, 0xd4, 0x4e, 0x18, 0x81, 0xfc,
	0x5d, 0x8e, 0x67, 0x67, 0x64, 0x27, 0x9b, 0x06, 0x15, 0x13, 0xde, 0x57, 0xf4, 0x05, 0x4c, 0x70,
	0x5b, 0xae, 0x3a, 0x92, 0xc0, 0xc5, 0x56, 0x15, 0x6d, 0x59, 0x0d, 0xbf, 0x6b, 0x28, 0xe9, 0x07,
	0x88, 0x90, 0x22, 0x6f, 0x20, 0x6c, 0x54, 0xe7, 0xde, 0x5f, 0xa6, 0xb3, 0x5b, 0x3f, 0x20, 0x57,
	0x1d, 0x47, 0xfa, 0xd3, 0x05, 0x44, 0xd2, 0xf6, 0xd3, 0x5f, 0x3e, 0x3c, 0x3c, 0xc3, 0x2b, 0xd9,
	0x1c, 0xf2, 0xad, 0x24, 0x1f, 0x21, 0x76, 0xa9, 0x21, 0xcf, 0xfe, 0x1f, 0xf8, 0x4f, 0x9e, 0xe8,
	0x35, 0x73, 0x69, 0x64, 0x43, 0x1a, 0xd9, 0xd2, 0xa6, 0x91, 0xbc, 0x87, 0x18, 0x6f, 0xd6, 0xe4,
	0xd1, 0x88, 0xa7, 0x31, 0xe9, 0xdc, 0xdf, 0xc4, 0xd8, 0x79, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x01, 0x84, 0xe9, 0xe3, 0x01, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TerminalUIServiceClient is the client API for TerminalUIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TerminalUIServiceClient interface {
	Output(ctx context.Context, in *TerminalUI_OutputRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Events(ctx context.Context, opts ...grpc.CallOption) (TerminalUIService_EventsClient, error)
}

type terminalUIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTerminalUIServiceClient(cc grpc.ClientConnInterface) TerminalUIServiceClient {
	return &terminalUIServiceClient{cc}
}

func (c *terminalUIServiceClient) Output(ctx context.Context, in *TerminalUI_OutputRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.TerminalUIService/Output", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalUIServiceClient) Events(ctx context.Context, opts ...grpc.CallOption) (TerminalUIService_EventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TerminalUIService_serviceDesc.Streams[0], "/proto.TerminalUIService/Events", opts...)
	if err != nil {
		return nil, err
	}
	x := &terminalUIServiceEventsClient{stream}
	return x, nil
}

type TerminalUIService_EventsClient interface {
	Send(*TerminalUI_Event) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type terminalUIServiceEventsClient struct {
	grpc.ClientStream
}

func (x *terminalUIServiceEventsClient) Send(m *TerminalUI_Event) error {
	return x.ClientStream.SendMsg(m)
}

func (x *terminalUIServiceEventsClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TerminalUIServiceServer is the server API for TerminalUIService service.
type TerminalUIServiceServer interface {
	Output(context.Context, *TerminalUI_OutputRequest) (*empty.Empty, error)
	Events(TerminalUIService_EventsServer) error
}

// UnimplementedTerminalUIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTerminalUIServiceServer struct {
}

func (*UnimplementedTerminalUIServiceServer) Output(ctx context.Context, req *TerminalUI_OutputRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Output not implemented")
}
func (*UnimplementedTerminalUIServiceServer) Events(srv TerminalUIService_EventsServer) error {
	return status.Errorf(codes.Unimplemented, "method Events not implemented")
}

func RegisterTerminalUIServiceServer(s *grpc.Server, srv TerminalUIServiceServer) {
	s.RegisterService(&_TerminalUIService_serviceDesc, srv)
}

func _TerminalUIService_Output_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminalUI_OutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalUIServiceServer).Output(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TerminalUIService/Output",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalUIServiceServer).Output(ctx, req.(*TerminalUI_OutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalUIService_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TerminalUIServiceServer).Events(&terminalUIServiceEventsServer{stream})
}

type TerminalUIService_EventsServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*TerminalUI_Event, error)
	grpc.ServerStream
}

type terminalUIServiceEventsServer struct {
	grpc.ServerStream
}

func (x *terminalUIServiceEventsServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *terminalUIServiceEventsServer) Recv() (*TerminalUI_Event, error) {
	m := new(TerminalUI_Event)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TerminalUIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TerminalUIService",
	HandlerType: (*TerminalUIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Output",
			Handler:    _TerminalUIService_Output_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _TerminalUIService_Events_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "terminal.proto",
}
