// Code generated by protoc-gen-go. DO NOT EDIT.
// source: waypoint/builtin/google/cloudrun/plugin.proto

package cloudrun

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Deployment struct {
	Url                  string               `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Resource             *Deployment_Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	RevisionId           string               `protobuf:"bytes,3,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Deployment) Reset()         { *m = Deployment{} }
func (m *Deployment) String() string { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()    {}
func (*Deployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f907789efce9e4b, []int{0}
}

func (m *Deployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deployment.Unmarshal(m, b)
}
func (m *Deployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deployment.Marshal(b, m, deterministic)
}
func (m *Deployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deployment.Merge(m, src)
}
func (m *Deployment) XXX_Size() int {
	return xxx_messageInfo_Deployment.Size(m)
}
func (m *Deployment) XXX_DiscardUnknown() {
	xxx_messageInfo_Deployment.DiscardUnknown(m)
}

var xxx_messageInfo_Deployment proto.InternalMessageInfo

func (m *Deployment) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Deployment) GetResource() *Deployment_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *Deployment) GetRevisionId() string {
	if m != nil {
		return m.RevisionId
	}
	return ""
}

type Deployment_Resource struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Deployment_Resource) Reset()         { *m = Deployment_Resource{} }
func (m *Deployment_Resource) String() string { return proto.CompactTextString(m) }
func (*Deployment_Resource) ProtoMessage()    {}
func (*Deployment_Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f907789efce9e4b, []int{0, 0}
}

func (m *Deployment_Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deployment_Resource.Unmarshal(m, b)
}
func (m *Deployment_Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deployment_Resource.Marshal(b, m, deterministic)
}
func (m *Deployment_Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deployment_Resource.Merge(m, src)
}
func (m *Deployment_Resource) XXX_Size() int {
	return xxx_messageInfo_Deployment_Resource.Size(m)
}
func (m *Deployment_Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Deployment_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Deployment_Resource proto.InternalMessageInfo

func (m *Deployment_Resource) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Deployment_Resource) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Deployment_Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Release struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Release) Reset()         { *m = Release{} }
func (m *Release) String() string { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()    {}
func (*Release) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f907789efce9e4b, []int{1}
}

func (m *Release) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Release.Unmarshal(m, b)
}
func (m *Release) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Release.Marshal(b, m, deterministic)
}
func (m *Release) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Release.Merge(m, src)
}
func (m *Release) XXX_Size() int {
	return xxx_messageInfo_Release.Size(m)
}
func (m *Release) XXX_DiscardUnknown() {
	xxx_messageInfo_Release.DiscardUnknown(m)
}

var xxx_messageInfo_Release proto.InternalMessageInfo

func (m *Release) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*Deployment)(nil), "google.cloudrun.Deployment")
	proto.RegisterType((*Deployment_Resource)(nil), "google.cloudrun.Deployment.Resource")
	proto.RegisterType((*Release)(nil), "google.cloudrun.Release")
}

func init() {
	proto.RegisterFile("waypoint/builtin/google/cloudrun/plugin.proto", fileDescriptor_6f907789efce9e4b)
}

var fileDescriptor_6f907789efce9e4b = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x89, 0x27, 0x5e, 0x6e, 0xae, 0x50, 0xb6, 0x0a, 0x67, 0x61, 0x08, 0x16, 0xd7, 0xb8,
	0x01, 0xfd, 0x03, 0x22, 0x36, 0xb6, 0x8b, 0x95, 0x8d, 0xe4, 0x92, 0x21, 0xac, 0xcc, 0xcd, 0x2c,
	0x9b, 0x5d, 0xe5, 0x7e, 0xa9, 0x7f, 0x47, 0x8c, 0xd9, 0x08, 0x5a, 0x5c, 0x37, 0xb3, 0x6f, 0xdf,
	0xc7, 0x9b, 0x07, 0x37, 0x1f, 0xcd, 0xc1, 0x89, 0xe5, 0x50, 0xef, 0xa2, 0xa5, 0x60, 0xb9, 0xee,
	0x45, 0x7a, 0xc2, 0xba, 0x25, 0x89, 0x9d, 0x8f, 0x5c, 0x3b, 0x8a, 0xbd, 0x65, 0xed, 0xbc, 0x04,
	0x51, 0xe7, 0x3f, 0xaa, 0x4e, 0x6a, 0xf5, 0x99, 0x01, 0x3c, 0xa2, 0x23, 0x39, 0xec, 0x91, 0x83,
	0xba, 0x80, 0x45, 0xf4, 0x54, 0x64, 0x65, 0xb6, 0x5d, 0x99, 0xef, 0x51, 0xdd, 0x43, 0xee, 0x71,
	0x90, 0xe8, 0x5b, 0x2c, 0x4e, 0xca, 0x6c, 0xbb, 0xbe, 0xbd, 0xd6, 0x7f, 0x20, 0xfa, 0x17, 0xa0,
	0xcd, 0xf4, 0xd7, 0xcc, 0x2e, 0x75, 0x05, 0x6b, 0x8f, 0xef, 0x76, 0xb0, 0xc2, 0xaf, 0xb6, 0x2b,
	0x16, 0x23, 0x1b, 0xd2, 0xd3, 0x53, 0xb7, 0x79, 0x86, 0x3c, 0xd9, 0xd4, 0x06, 0x72, 0x92, 0xb6,
	0x09, 0x56, 0x78, 0x4a, 0x31, 0xef, 0xaa, 0x80, 0xa5, 0xf3, 0xf2, 0x86, 0x6d, 0x18, 0x93, 0xac,
	0x4c, 0x5a, 0x95, 0x82, 0x53, 0x6e, 0xf6, 0x38, 0xb1, 0xc7, 0xb9, 0xba, 0x84, 0xa5, 0x41, 0xc2,
	0x66, 0xc0, 0xff, 0x57, 0x3d, 0x54, 0x2f, 0xe5, 0xb1, 0xe2, 0x76, 0x67, 0x63, 0x65, 0x77, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x85, 0xef, 0xb5, 0xc5, 0x63, 0x01, 0x00, 0x00,
}
