// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Deployment is an autogenerated mock type for the Deployment type
type Deployment struct {
	mock.Mock
}
