// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: waypoint/builtin/nomad/canary/plugin.proto

package canary

import (
	opaqueany "github.com/hashicorp/opaqueany"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Release struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url           string         `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	ResourceState *opaqueany.Any `protobuf:"bytes,2,opt,name=resource_state,json=resourceState,proto3" json:"resource_state,omitempty"`
}

func (x *Release) Reset() {
	*x = Release{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waypoint_builtin_nomad_canary_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_waypoint_builtin_nomad_canary_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_waypoint_builtin_nomad_canary_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Release) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Release) GetResourceState() *opaqueany.Any {
	if x != nil {
		return x.ResourceState
	}
	return nil
}

var File_waypoint_builtin_nomad_canary_plugin_proto protoreflect.FileDescriptor

var file_waypoint_builtin_nomad_canary_plugin_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x77, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x74,
	0x69, 0x6e, 0x2f, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x2f, 0x63, 0x61, 0x6e, 0x61, 0x72, 0x79, 0x2f,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x61,
	0x6e, 0x61, 0x72, 0x79, 0x1a, 0x13, 0x6f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x61, 0x6e, 0x79, 0x2f,
	0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x07, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x35, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x61, 0x6e, 0x79, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0d,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x1f, 0x5a,
	0x1d, 0x77, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69,
	0x6e, 0x2f, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x2f, 0x63, 0x61, 0x6e, 0x61, 0x72, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_waypoint_builtin_nomad_canary_plugin_proto_rawDescOnce sync.Once
	file_waypoint_builtin_nomad_canary_plugin_proto_rawDescData = file_waypoint_builtin_nomad_canary_plugin_proto_rawDesc
)

func file_waypoint_builtin_nomad_canary_plugin_proto_rawDescGZIP() []byte {
	file_waypoint_builtin_nomad_canary_plugin_proto_rawDescOnce.Do(func() {
		file_waypoint_builtin_nomad_canary_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_waypoint_builtin_nomad_canary_plugin_proto_rawDescData)
	})
	return file_waypoint_builtin_nomad_canary_plugin_proto_rawDescData
}

var file_waypoint_builtin_nomad_canary_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_waypoint_builtin_nomad_canary_plugin_proto_goTypes = []interface{}{
	(*Release)(nil),       // 0: canary.Release
	(*opaqueany.Any)(nil), // 1: opaqueany.Any
}
var file_waypoint_builtin_nomad_canary_plugin_proto_depIdxs = []int32{
	1, // 0: canary.Release.resource_state:type_name -> opaqueany.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_waypoint_builtin_nomad_canary_plugin_proto_init() }
func file_waypoint_builtin_nomad_canary_plugin_proto_init() {
	if File_waypoint_builtin_nomad_canary_plugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_waypoint_builtin_nomad_canary_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Release); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waypoint_builtin_nomad_canary_plugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waypoint_builtin_nomad_canary_plugin_proto_goTypes,
		DependencyIndexes: file_waypoint_builtin_nomad_canary_plugin_proto_depIdxs,
		MessageInfos:      file_waypoint_builtin_nomad_canary_plugin_proto_msgTypes,
	}.Build()
	File_waypoint_builtin_nomad_canary_plugin_proto = out.File
	file_waypoint_builtin_nomad_canary_plugin_proto_rawDesc = nil
	file_waypoint_builtin_nomad_canary_plugin_proto_goTypes = nil
	file_waypoint_builtin_nomad_canary_plugin_proto_depIdxs = nil
}
