name: hashicorp/waypoint/frontend
on:
  push:
    branches:
    - main
env:
  ALGOLIA_API_KEY: xxxxxxx
  GH_DOCKER_PASS: xxxxxxx
  GH_DOCKER_USER: xxxxxxx
  SLACK_APPROVAL_NOTIFICATION_WEBHOOK_URL: xxxxxxx
  SLACK_WEBHOOK: xxxxxxx
jobs:
  frontend-cache:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/circleci/node:14-browsers
    env:
      TEST_RESULTS_DIR: "/tmp/test-results"
      GOTESTSUM_RELEASE: 1.8.2
      EMAIL: noreply@hashicorp.com
      GIT_AUTHOR_NAME: circleci-waypoint
      GIT_COMMITTER_NAME: circleci-waypoint
      BASH_ENV: "/home/circleci/project/.circleci/bash_env.sh"
      DOCKER_BUILDKIT: 1
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/md5uilib"
    - name: restore_cache
      uses: actions/cache@v3.3.1
      with:
        key: waypoint-ui-v1-{{ checksum "ui/yarn.lock" }}-{{ checksum "uilib.md5" }}
        path: |-
          ui/node_modules
          ui/lib/node_modules
    - name: install yarn packages
      run: cd ui && yarn install
    - uses: "./.github/actions/notify_main_failure"
  frontend-lint:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/circleci/node:14-browsers
    needs:
    - frontend-cache
    env:
      TEST_RESULTS_DIR: "/tmp/test-results"
      GOTESTSUM_RELEASE: 1.8.2
      EMAIL: noreply@hashicorp.com
      GIT_AUTHOR_NAME: circleci-waypoint
      GIT_COMMITTER_NAME: circleci-waypoint
      BASH_ENV: "/home/circleci/project/.circleci/bash_env.sh"
      DOCKER_BUILDKIT: 1
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/md5uilib"
    - name: restore_cache
      uses: actions/cache@v3.3.1
      with:
        key: waypoint-ui-v1-{{ checksum "ui/yarn.lock" }}-{{ checksum "uilib.md5" }}
    - run: yarn lint
      working-directory: ui
    - uses: "./.github/actions/notify_main_failure"
  ember-build-tests:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/circleci/node:14-browsers
    needs:
    - frontend-lint
    env:
      JOBS: 1
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/md5uilib"
    - name: restore_cache
      uses: actions/cache@v3.3.1
      with:
        key: waypoint-ui-v1-{{ checksum "ui/yarn.lock" }}-{{ checksum "uilib.md5" }}
    - run: cd ui && yarn build:test
    - uses: actions/upload-artifact@v3.1.1
      with:
        path: ui/dist
    - uses: "./.github/actions/notify_main_failure"
  ember-test:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/circleci/node:14-browsers
    needs:
    - ember-build-tests
    env:
      EMBER_TEST_REPORT: test-results/report-oss.xml
      EMBER_TEST_PARALLEL: 'true'
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/md5uilib"
    - name: restore_cache
      uses: actions/cache@v3.3.1
      with:
        key: waypoint-ui-v1-{{ checksum "ui/yarn.lock" }}-{{ checksum "uilib.md5" }}
    - uses: actions/download-artifact@v3.0.1
      with:
        path: ui
    - run: yarn test:ember:ci
      working-directory: ui
    - uses: actions/upload-artifact@v3.1.1
      with:
        path: ui/test-results
