name: frontend
on:
  push:
  pull_request:

jobs:
  frontend-cache:
    runs-on: ubuntu-latest
    outputs:
      yarn-cache-key: ${{ steps.set-cache-key.outputs.cache-key}}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: set-cache-key
        id: set-cache-key
        run: echo "cache-key=waypoint-ui-v1-${{ hashFiles('ui/yarn.lock', 'ui/lib/**') }}" | tee -a "${GITHUB_OUTPUT}"

      - name: Initialize UI cache
        id: ui-cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          key: "${{ steps.set-cache-key.outputs.cache-key }}"
          path: |- 
            ui/node_modules
            ui/lib/node_modules

      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        if: steps.ui-cache.outputs.cache-hit == false
        with:
          node-version: 14

      - name: install yarn packages
        if: steps.ui-cache.outputs.cache-hit == false
        run: yarn install
        working-directory: ui


  frontend-lint:
    runs-on: ubuntu-latest
    needs:
      - frontend-cache
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version: 14

      - name: restore-cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          key: ${{ needs.frontend-cache.outputs.yarn-cache-key }}
          path: |- 
            ui/node_modules
            ui/lib/node_modules

      - run: yarn lint
        working-directory: ui

  ember-tests:
    runs-on: ubuntu-latest
    env:
      EMBER_TEST_REPORT: test-results/report-oss.xml
      EMBER_TEST_PARALLEL: 'true'
    needs:
      - frontend-cache
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version: 14

      - name: restore-cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          key: ${{ needs.frontend-cache.outputs.yarn-cache-key }}
          path: |- 
            ui/node_modules
            ui/lib/node_modules

      - name: build:test
        run: yarn build:test
        working-directory: ui
      
      - name: test:ember:ci
        run: yarn test:ember:ci
        working-directory: ui

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          path: ui/test-results

permissions:
  contents: read
