name: integrations-hcl
on:
  pull_request:
# FIXME: Disabling for the purposes of PR #4617 validation, but re-enable before merging!
#    paths: [builtin/**]
jobs:
  generate-integration-hcl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: go.mod
      - name: Download go modules
        run: go mod download
      - run: make gen/integrations-hcl
      - run: git status
      - run: |
          if ! git diff --exit-code builtin > /dev/null; then
            echo "Built-in integration documentation has unstaged changes. This is because you have modified"
            echo "docs for a builtin plugin that must be reflected in the website."
            echo
            echo "Run the following make command:"
            echo
            echo "make gen/integrations-hcl"
            echo
            echo "And then validate that the corresponding website pages look acceptable."
            git status
            exit 1
          fi
permissions:
  contents: read
