name: integrations-hcl
on:
  pull_request:
    paths: [builtin/**]
jobs:
  generate-integration-hcl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
      - name: Download go modules
        run: go mod download
      - run: make gen/integrations-hcl
      - run: git status
      - run: |
          if ! git diff --exit-code builtin > /dev/null; then
            echo "Built-in integration documentation has unstaged changes. This is because you have modified"
            echo "docs for a builtin plugin that must be reflected in the website."
            echo
            echo "Run the following make command:"
            echo
            echo "make gen/integrations-hcl"
            echo
            echo "And then validate that the corresponding website pages look acceptable."
            git status
            exit 1
          fi
permissions:
  contents: read
