name: json-docs
on:
  pull_request:
    paths: [embedJson/**]

jobs:
  generate-json-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
      - run: go mod download
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          path: "."
      - name: generate json plugin docs
        run: go run ./cmd/waypoint docs -json
      - run: rm waypoint-restore.db.lock; git status
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          path: "embedJson"
          name: docs

  check-json-docs:
    runs-on: ubuntu-latest
    needs:
      - generate-json-docs
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          path: "embedJson"
          name: docs
      - run: git status
      - run: |
          if ! git diff --exit-code embedJson/gen > /dev/null; then
            echo "Website directory has unstaged json changes. This is because you have modified doc strings"
            echo "that must be reflected in the json docs. Run the following make command:"
            echo
            echo "make gen/website-mdx"
            echo
            echo "And then validate that the corresponding json docs look acceptable."
            git status
            exit 1
          fi

permissions:
  contents: read
