name: "size"
on:
  pull_request:
    branches:
      - main
    paths:
      - ui/**
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@071d67370c0f5be4778859936b86a7b7b8709cda
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: ui/
