name: website-mdx
# FIMXE: If this workflow is just a test, should we only run on pull_request instead of push? Does that convey intent correctly?
on:
  pull_request:

jobs:
  generate-website-mdx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          path: "."
      - name: generate plugin docs
        run: go run ./cmd/waypoint docs -website-mdx
      - name: generate cli docs
        run: go run ./tools/gendocs
      - run: rm waypoint-restore.db.lock; git status
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          path: "./."
# FIXME: This entire workflow exists to check if our website code compiles, so do we need to notify at all?
#      - uses: hashicorp/actions-slack-status@v1
#        if: failure() && github.ref == 'refs/heads/main'
#        with:
#          failure-message: website generation failed
#          status: ${{job.status}}
#          slack-webhook-url: ${{secrets.SLACK_WEBHOOK_URL}}

  check-website-mdx:
    runs-on: ubuntu-latest
    needs:
      - generate-website-mdx
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          path: "."
      - run: git status
      - run: cd ./website; npm i -g npm@latest; npm install
      - run: cd ./website; npx --no-install next-hashicorp format
      - run: |
          if ! git diff --exit-code website/content > /dev/null; then
            echo "Website directory has unstaged mdx changes. This is because you have modified doc strings"
            echo "that must be reflected in the website. Run the following make command:"
            echo
            echo "make gen/website-mdx"
            echo
            echo "And then validate that the corresponding website pages look acceptable."
            git status
            exit 1
          fi
# FIXME: This entire workflow exists to check if our website code compiles, so do we need to notify at all?
#      - uses: hashicorp/actions-slack-status@v1
#        if: failure() && github.ref == 'refs/heads/main'
#        with:
#          failure-message: website directory has unstaged mdx changes
#          status: ${{job.status}}
#          slack-webhook-url: ${{secrets.SLACK_WEBHOOK_URL}}

permissions:
  contents: read
